/**
 * generated by Xtext 2.12.0
 */
package org.omg.sysml.usage.ui.contentassist;

import org.omg.sysml.usage.ui.contentassist.AbstractSysMLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SysMLProposalProvider extends AbstractSysMLProposalProvider {
}
