/*
 * generated by Xtext 2.18.0.M3
 */
package org.omg.kerml.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.omg.kerml.xtext.parser.antlr.internal.InternalKerMLParser;
import org.omg.kerml.xtext.services.KerMLGrammarAccess;

public class KerMLParser extends AbstractAntlrParser {

	@Inject
	private KerMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKerMLParser createParser(XtextTokenStream stream) {
		return new InternalKerMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Unit";
	}

	public KerMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KerMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
