/**
 * generated by Xtext 2.12.0
 */
package org.omg.sysml.owl.owl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Datatype</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.omg.sysml.owl.owl.OwlPackage#getDatatype()
 * @model
 * @generated
 */
public interface Datatype extends Entity
{
} // Datatype
