/**
 * generated by Xtext 2.12.0
 */
package org.omg.sysml.owl.owl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Facet Restriction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.omg.sysml.owl.owl.FacetRestriction#getConstrainingFacet <em>Constraining Facet</em>}</li>
 *   <li>{@link org.omg.sysml.owl.owl.FacetRestriction#getRestrictionValue <em>Restriction Value</em>}</li>
 * </ul>
 *
 * @see org.omg.sysml.owl.owl.OwlPackage#getFacetRestriction()
 * @model
 * @generated
 */
public interface FacetRestriction extends EObject
{
  /**
   * Returns the value of the '<em><b>Constraining Facet</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraining Facet</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraining Facet</em>' attribute.
   * @see #setConstrainingFacet(String)
   * @see org.omg.sysml.owl.owl.OwlPackage#getFacetRestriction_ConstrainingFacet()
   * @model
   * @generated
   */
  String getConstrainingFacet();

  /**
   * Sets the value of the '{@link org.omg.sysml.owl.owl.FacetRestriction#getConstrainingFacet <em>Constraining Facet</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraining Facet</em>' attribute.
   * @see #getConstrainingFacet()
   * @generated
   */
  void setConstrainingFacet(String value);

  /**
   * Returns the value of the '<em><b>Restriction Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Restriction Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Restriction Value</em>' containment reference.
   * @see #setRestrictionValue(Literal)
   * @see org.omg.sysml.owl.owl.OwlPackage#getFacetRestriction_RestrictionValue()
   * @model containment="true"
   * @generated
   */
  Literal getRestrictionValue();

  /**
   * Sets the value of the '{@link org.omg.sysml.owl.owl.FacetRestriction#getRestrictionValue <em>Restriction Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Restriction Value</em>' containment reference.
   * @see #getRestrictionValue()
   * @generated
   */
  void setRestrictionValue(Literal value);

} // FacetRestriction
