/**
 * generated by Xtext 2.12.0
 */
package org.omg.sysml.owl.owl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inverse Object Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.omg.sysml.owl.owl.InverseObjectProperties#getObjectPropertyExpression1 <em>Object Property Expression1</em>}</li>
 *   <li>{@link org.omg.sysml.owl.owl.InverseObjectProperties#getObjectPropertyExpression2 <em>Object Property Expression2</em>}</li>
 * </ul>
 *
 * @see org.omg.sysml.owl.owl.OwlPackage#getInverseObjectProperties()
 * @model
 * @generated
 */
public interface InverseObjectProperties extends ObjectPropertyAxiom
{
  /**
   * Returns the value of the '<em><b>Object Property Expression1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object Property Expression1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object Property Expression1</em>' containment reference.
   * @see #setObjectPropertyExpression1(ObjectPropertyExpression)
   * @see org.omg.sysml.owl.owl.OwlPackage#getInverseObjectProperties_ObjectPropertyExpression1()
   * @model containment="true"
   * @generated
   */
  ObjectPropertyExpression getObjectPropertyExpression1();

  /**
   * Sets the value of the '{@link org.omg.sysml.owl.owl.InverseObjectProperties#getObjectPropertyExpression1 <em>Object Property Expression1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object Property Expression1</em>' containment reference.
   * @see #getObjectPropertyExpression1()
   * @generated
   */
  void setObjectPropertyExpression1(ObjectPropertyExpression value);

  /**
   * Returns the value of the '<em><b>Object Property Expression2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object Property Expression2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object Property Expression2</em>' containment reference.
   * @see #setObjectPropertyExpression2(ObjectPropertyExpression)
   * @see org.omg.sysml.owl.owl.OwlPackage#getInverseObjectProperties_ObjectPropertyExpression2()
   * @model containment="true"
   * @generated
   */
  ObjectPropertyExpression getObjectPropertyExpression2();

  /**
   * Sets the value of the '{@link org.omg.sysml.owl.owl.InverseObjectProperties#getObjectPropertyExpression2 <em>Object Property Expression2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object Property Expression2</em>' containment reference.
   * @see #getObjectPropertyExpression2()
   * @generated
   */
  void setObjectPropertyExpression2(ObjectPropertyExpression value);

} // InverseObjectProperties
