/**
 * generated by Xtext 2.12.0
 */
package org.omg.sysml.owl.owl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Named Individual Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.omg.sysml.owl.owl.OwlPackage#getNamedIndividualReference()
 * @model
 * @generated
 */
public interface NamedIndividualReference extends IndividualReference
{
} // NamedIndividualReference
