/*
 * generated by Xtext 2.16.0
 */
package org.omg.sysml.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.omg.sysml.ide.contentassist.antlr.internal.InternalAlfParser;
import org.omg.sysml.services.AlfGrammarAccess;

public class AlfParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AlfGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AlfGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getUnitDefinitionAccess().getAlternatives(), "rule__UnitDefinition__Alternatives");
			builder.put(grammarAccess.getUnitPrefixAccess().getAlternatives_0(), "rule__UnitPrefix__Alternatives_0");
			builder.put(grammarAccess.getPackageImportAccess().getAlternatives_3(), "rule__PackageImport__Alternatives_3");
			builder.put(grammarAccess.getPackageImportAccess().getAlternatives_3_0_1(), "rule__PackageImport__Alternatives_3_0_1");
			builder.put(grammarAccess.getNonFeatureDefinitionAccess().getAlternatives(), "rule__NonFeatureDefinition__Alternatives");
			builder.put(grammarAccess.getPackageDefinitionAccess().getAlternatives_3(), "rule__PackageDefinition__Alternatives_3");
			builder.put(grammarAccess.getPackageMemberAccess().getAlternatives_1(), "rule__PackageMember__Alternatives_1");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getAlternatives(), "rule__NonFeatureMemberElement__Alternatives");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getAlternatives(), "rule__FeaturePackageMemberElement__Alternatives");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getAlternatives_2_0(), "rule__FeaturePackageMemberElement__Alternatives_2_0");
			builder.put(grammarAccess.getCategoryBodyAccess().getAlternatives(), "rule__CategoryBody__Alternatives");
			builder.put(grammarAccess.getCategoryBodyAccess().getAlternatives_1_1(), "rule__CategoryBody__Alternatives_1_1");
			builder.put(grammarAccess.getCategoryMemberAccess().getAlternatives(), "rule__CategoryMember__Alternatives");
			builder.put(grammarAccess.getFeatureCategoryMemberAccess().getAlternatives_1(), "rule__FeatureCategoryMember__Alternatives_1");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getAlternatives(), "rule__FeatureMemberElement__Alternatives");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getAlternatives_0_0(), "rule__FeatureMemberElement__Alternatives_0_0");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getAlternatives_0_2(), "rule__FeatureMemberElement__Alternatives_0_2");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getAlternatives_1_1(), "rule__FeatureMemberElement__Alternatives_1_1");
			builder.put(grammarAccess.getAssociationBodyAccess().getAlternatives(), "rule__AssociationBody__Alternatives");
			builder.put(grammarAccess.getAssociationBodyAccess().getAlternatives_1_1(), "rule__AssociationBody__Alternatives_1_1");
			builder.put(grammarAccess.getAssociationMemberAccess().getAlternatives(), "rule__AssociationMember__Alternatives");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getAlternatives_1(), "rule__AssociationEndFeatureMember__Alternatives_1");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getAlternatives_1_0_1(), "rule__AssociationEndFeatureMember__Alternatives_1_0_1");
			builder.put(grammarAccess.getFeatureDefinitionAccess().getAlternatives(), "rule__FeatureDefinition__Alternatives");
			builder.put(grammarAccess.getTypePartAccess().getAlternatives_0_2(), "rule__TypePart__Alternatives_0_2");
			builder.put(grammarAccess.getSubsettingPartAccess().getAlternatives(), "rule__SubsettingPart__Alternatives");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getAlternatives_0(), "rule__ConnectorDefinition__Alternatives_0");
			builder.put(grammarAccess.getConnectorEndAccess().getAlternatives(), "rule__ConnectorEnd__Alternatives");
			builder.put(grammarAccess.getParameterDefinitionAccess().getAlternatives_1(), "rule__ParameterDefinition__Alternatives_1");
			builder.put(grammarAccess.getBinaryExpressionAccess().getAlternatives_1_1(), "rule__BinaryExpression__Alternatives_1_1");
			builder.put(grammarAccess.getBinaryOperatorAccess().getAlternatives(), "rule__BinaryOperator__Alternatives");
			builder.put(grammarAccess.getUnaryExpressionAccess().getAlternatives(), "rule__UnaryExpression__Alternatives");
			builder.put(grammarAccess.getUnaryOperatorAccess().getAlternatives(), "rule__UnaryOperator__Alternatives");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
			builder.put(grammarAccess.getTupleAccess().getAlternatives(), "rule__Tuple__Alternatives");
			builder.put(grammarAccess.getLiteralExpressionAccess().getAlternatives(), "rule__LiteralExpression__Alternatives");
			builder.put(grammarAccess.getRealValueAccess().getAlternatives(), "rule__RealValue__Alternatives");
			builder.put(grammarAccess.getRealValueAccess().getAlternatives_0_2(), "rule__RealValue__Alternatives_0_2");
			builder.put(grammarAccess.getUnlimitedNaturalLiteralExpressionAccess().getAlternatives(), "rule__UnlimitedNaturalLiteralExpression__Alternatives");
			builder.put(grammarAccess.getNameAccess().getAlternatives(), "rule__Name__Alternatives");
			builder.put(grammarAccess.getQualifiedNameAccess().getAlternatives(), "rule__QualifiedName__Alternatives");
			builder.put(grammarAccess.getPackageElementVisibilityIndicatorAccess().getAlternatives(), "rule__PackageElementVisibilityIndicator__Alternatives");
			builder.put(grammarAccess.getVisibilityIndicatorAccess().getAlternatives(), "rule__VisibilityIndicator__Alternatives");
			builder.put(grammarAccess.getFeatureDirectionAccess().getAlternatives(), "rule__FeatureDirection__Alternatives");
			builder.put(grammarAccess.getPackageUnitDefinitionAccess().getGroup(), "rule__PackageUnitDefinition__Group__0");
			builder.put(grammarAccess.getClassUnitDefinitionAccess().getGroup(), "rule__ClassUnitDefinition__Group__0");
			builder.put(grammarAccess.getObjectClassUnitDefinitionAccess().getGroup(), "rule__ObjectClassUnitDefinition__Group__0");
			builder.put(grammarAccess.getValueClassUnitDefinitionAccess().getGroup(), "rule__ValueClassUnitDefinition__Group__0");
			builder.put(grammarAccess.getAssociationUnitDefinitionAccess().getGroup(), "rule__AssociationUnitDefinition__Group__0");
			builder.put(grammarAccess.getFeatureUnitDefinitionAccess().getGroup(), "rule__FeatureUnitDefinition__Group__0");
			builder.put(grammarAccess.getUnitPrefixAccess().getGroup(), "rule__UnitPrefix__Group__0");
			builder.put(grammarAccess.getPackageImportAccess().getGroup(), "rule__PackageImport__Group__0");
			builder.put(grammarAccess.getPackageImportAccess().getGroup_3_0(), "rule__PackageImport__Group_3_0__0");
			builder.put(grammarAccess.getPackageImportAccess().getGroup_3_1(), "rule__PackageImport__Group_3_1__0");
			builder.put(grammarAccess.getPackageImportAccess().getGroup_3_2(), "rule__PackageImport__Group_3_2__0");
			builder.put(grammarAccess.getElementImportAccess().getGroup(), "rule__ElementImport__Group__0");
			builder.put(grammarAccess.getElementImportAccess().getGroup_3(), "rule__ElementImport__Group_3__0");
			builder.put(grammarAccess.getPackageDefinitionAccess().getGroup(), "rule__PackageDefinition__Group__0");
			builder.put(grammarAccess.getPackageMemberAccess().getGroup(), "rule__PackageMember__Group__0");
			builder.put(grammarAccess.getPackageMemberPrefixAccess().getGroup(), "rule__PackageMemberPrefix__Group__0");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getGroup_1(), "rule__NonFeatureMemberElement__Group_1__0");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getGroup_2(), "rule__NonFeatureMemberElement__Group_2__0");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getGroup_3(), "rule__NonFeatureMemberElement__Group_3__0");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getGroup_4(), "rule__NonFeatureMemberElement__Group_4__0");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getGroup_5(), "rule__NonFeatureMemberElement__Group_5__0");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getGroup_6(), "rule__NonFeatureMemberElement__Group_6__0");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getGroup_7(), "rule__NonFeatureMemberElement__Group_7__0");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getGroup_8(), "rule__NonFeatureMemberElement__Group_8__0");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getGroup_8_2(), "rule__NonFeatureMemberElement__Group_8_2__0");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getGroup_0(), "rule__FeaturePackageMemberElement__Group_0__0");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getGroup_1(), "rule__FeaturePackageMemberElement__Group_1__0");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getGroup_2(), "rule__FeaturePackageMemberElement__Group_2__0");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getGroup_2_0_0(), "rule__FeaturePackageMemberElement__Group_2_0_0__0");
			builder.put(grammarAccess.getCategoryBodyAccess().getGroup_1(), "rule__CategoryBody__Group_1__0");
			builder.put(grammarAccess.getNonFeatureCategoryMemberAccess().getGroup(), "rule__NonFeatureCategoryMember__Group__0");
			builder.put(grammarAccess.getFeatureCategoryMemberAccess().getGroup(), "rule__FeatureCategoryMember__Group__0");
			builder.put(grammarAccess.getFeatureCategoryMemberAccess().getGroup_1_1(), "rule__FeatureCategoryMember__Group_1_1__0");
			builder.put(grammarAccess.getFeatureCategoryMemberAccess().getGroup_1_2(), "rule__FeatureCategoryMember__Group_1_2__0");
			builder.put(grammarAccess.getCategoryMemberPrefixAccess().getGroup(), "rule__CategoryMemberPrefix__Group__0");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getGroup_0(), "rule__FeatureMemberElement__Group_0__0");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getGroup_0_2_1(), "rule__FeatureMemberElement__Group_0_2_1__0");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getGroup_1(), "rule__FeatureMemberElement__Group_1__0");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getGroup_1_1_1(), "rule__FeatureMemberElement__Group_1_1_1__0");
			builder.put(grammarAccess.getClassDefinitionAccess().getGroup(), "rule__ClassDefinition__Group__0");
			builder.put(grammarAccess.getClassDeclarationAccess().getGroup(), "rule__ClassDeclaration__Group__0");
			builder.put(grammarAccess.getClassDeclarationCompletionAccess().getGroup(), "rule__ClassDeclarationCompletion__Group__0");
			builder.put(grammarAccess.getSpecializationListAccess().getGroup(), "rule__SpecializationList__Group__0");
			builder.put(grammarAccess.getSpecializationListAccess().getGroup_2(), "rule__SpecializationList__Group_2__0");
			builder.put(grammarAccess.getObjectClassDefinitionAccess().getGroup(), "rule__ObjectClassDefinition__Group__0");
			builder.put(grammarAccess.getObjectClassDeclarationAccess().getGroup(), "rule__ObjectClassDeclaration__Group__0");
			builder.put(grammarAccess.getValueClassDefinitionAccess().getGroup(), "rule__ValueClassDefinition__Group__0");
			builder.put(grammarAccess.getValueClassDeclarationAccess().getGroup(), "rule__ValueClassDeclaration__Group__0");
			builder.put(grammarAccess.getAssociationDefinitionAccess().getGroup(), "rule__AssociationDefinition__Group__0");
			builder.put(grammarAccess.getAssociationDeclarationAccess().getGroup(), "rule__AssociationDeclaration__Group__0");
			builder.put(grammarAccess.getAssociationBodyAccess().getGroup_1(), "rule__AssociationBody__Group_1__0");
			builder.put(grammarAccess.getAssociationFeatureMemberAccess().getGroup(), "rule__AssociationFeatureMember__Group__0");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getGroup(), "rule__AssociationEndFeatureMember__Group__0");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getGroup_1_0(), "rule__AssociationEndFeatureMember__Group_1_0__0");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getGroup_1_1(), "rule__AssociationEndFeatureMember__Group_1_1__0");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getGroup_1_2(), "rule__AssociationEndFeatureMember__Group_1_2__0");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getGroup_1_3(), "rule__AssociationEndFeatureMember__Group_1_3__0");
			builder.put(grammarAccess.getBehaviorDefinitionOrStubAccess().getGroup(), "rule__BehaviorDefinitionOrStub__Group__0");
			builder.put(grammarAccess.getBehaviorDeclarationAccess().getGroup(), "rule__BehaviorDeclaration__Group__0");
			builder.put(grammarAccess.getParameterListAccess().getGroup(), "rule__ParameterList__Group__0");
			builder.put(grammarAccess.getParameterListAccess().getGroup_1(), "rule__ParameterList__Group_1__0");
			builder.put(grammarAccess.getParameterListAccess().getGroup_1_1(), "rule__ParameterList__Group_1_1__0");
			builder.put(grammarAccess.getParameterMemberAccess().getGroup(), "rule__ParameterMember__Group__0");
			builder.put(grammarAccess.getFunctionDefinitionOrStubAccess().getGroup(), "rule__FunctionDefinitionOrStub__Group__0");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getGroup(), "rule__FunctionDeclaration__Group__0");
			builder.put(grammarAccess.getReturnParameterMemberAccess().getGroup(), "rule__ReturnParameterMember__Group__0");
			builder.put(grammarAccess.getNamedFeatureDefinitionAccess().getGroup(), "rule__NamedFeatureDefinition__Group__0");
			builder.put(grammarAccess.getUnnamedFeatureDefinitionAccess().getGroup(), "rule__UnnamedFeatureDefinition__Group__0");
			builder.put(grammarAccess.getFeatureBodyDefinitionAccess().getGroup(), "rule__FeatureBodyDefinition__Group__0");
			builder.put(grammarAccess.getFeatureDeclarationAccess().getGroup(), "rule__FeatureDeclaration__Group__0");
			builder.put(grammarAccess.getFeatureCompletionAccess().getGroup(), "rule__FeatureCompletion__Group__0");
			builder.put(grammarAccess.getFeatureCompletionAccess().getGroup_0(), "rule__FeatureCompletion__Group_0__0");
			builder.put(grammarAccess.getTypePartAccess().getGroup(), "rule__TypePart__Group__0");
			builder.put(grammarAccess.getTypePartAccess().getGroup_0(), "rule__TypePart__Group_0__0");
			builder.put(grammarAccess.getMultiplicityAccess().getGroup(), "rule__Multiplicity__Group__0");
			builder.put(grammarAccess.getMultiplicityAccess().getGroup_1(), "rule__Multiplicity__Group_1__0");
			builder.put(grammarAccess.getSubsettingPartAccess().getGroup_0(), "rule__SubsettingPart__Group_0__0");
			builder.put(grammarAccess.getSubsettingPartAccess().getGroup_0_1(), "rule__SubsettingPart__Group_0_1__0");
			builder.put(grammarAccess.getSubsettingPartAccess().getGroup_1(), "rule__SubsettingPart__Group_1__0");
			builder.put(grammarAccess.getSubsettingPartAccess().getGroup_1_1(), "rule__SubsettingPart__Group_1_1__0");
			builder.put(grammarAccess.getSubsetsAccess().getGroup(), "rule__Subsets__Group__0");
			builder.put(grammarAccess.getRedefinesAccess().getGroup(), "rule__Redefines__Group__0");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getGroup(), "rule__ConnectorDefinition__Group__0");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getGroup_0_0(), "rule__ConnectorDefinition__Group_0_0__0");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getGroup_0_0_0(), "rule__ConnectorDefinition__Group_0_0_0__0");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getGroup_0_0_0_1(), "rule__ConnectorDefinition__Group_0_0_0_1__0");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getGroup_0_1(), "rule__ConnectorDefinition__Group_0_1__0");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getGroup_0_1_1(), "rule__ConnectorDefinition__Group_0_1_1__0");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getGroup_0_1_6(), "rule__ConnectorDefinition__Group_0_1_6__0");
			builder.put(grammarAccess.getConnectorEndAccess().getGroup_0(), "rule__ConnectorEnd__Group_0__0");
			builder.put(grammarAccess.getConnectorEndAccess().getGroup_0_0(), "rule__ConnectorEnd__Group_0_0__0");
			builder.put(grammarAccess.getConnectorEndAccess().getGroup_1(), "rule__ConnectorEnd__Group_1__0");
			builder.put(grammarAccess.getConnectorEndAccess().getGroup_1_0(), "rule__ConnectorEnd__Group_1_0__0");
			builder.put(grammarAccess.getParameterDefinitionAccess().getGroup(), "rule__ParameterDefinition__Group__0");
			builder.put(grammarAccess.getBinaryExpressionAccess().getGroup(), "rule__BinaryExpression__Group__0");
			builder.put(grammarAccess.getBinaryExpressionAccess().getGroup_1(), "rule__BinaryExpression__Group_1__0");
			builder.put(grammarAccess.getBinaryExpressionAccess().getGroup_1_1_0(), "rule__BinaryExpression__Group_1_1_0__0");
			builder.put(grammarAccess.getBinaryExpressionAccess().getGroup_1_1_1(), "rule__BinaryExpression__Group_1_1_1__0");
			builder.put(grammarAccess.getUnaryExpressionAccess().getGroup_1(), "rule__UnaryExpression__Group_1__0");
			builder.put(grammarAccess.getSequenceAccessExpressionAccess().getGroup(), "rule__SequenceAccessExpression__Group__0");
			builder.put(grammarAccess.getSequenceAccessExpressionAccess().getGroup_1(), "rule__SequenceAccessExpression__Group_1__0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getGroup_5(), "rule__PrimaryExpression__Group_5__0");
			builder.put(grammarAccess.getInvocationExpressionAccess().getGroup(), "rule__InvocationExpression__Group__0");
			builder.put(grammarAccess.getPositionalTupleAccess().getGroup(), "rule__PositionalTuple__Group__0");
			builder.put(grammarAccess.getPositionalTupleAccess().getGroup_1(), "rule__PositionalTuple__Group_1__0");
			builder.put(grammarAccess.getNamedTupleAccess().getGroup(), "rule__NamedTuple__Group__0");
			builder.put(grammarAccess.getNamedTupleAccess().getGroup_1(), "rule__NamedTuple__Group_1__0");
			builder.put(grammarAccess.getSequenceConstructionExpressionAccess().getGroup(), "rule__SequenceConstructionExpression__Group__0");
			builder.put(grammarAccess.getSequenceConstructionExpressionAccess().getGroup_2(), "rule__SequenceConstructionExpression__Group_2__0");
			builder.put(grammarAccess.getSequenceConstructionExpressionAccess().getGroup_2_1(), "rule__SequenceConstructionExpression__Group_2_1__0");
			builder.put(grammarAccess.getNullExpressionAccess().getGroup(), "rule__NullExpression__Group__0");
			builder.put(grammarAccess.getRealValueAccess().getGroup_0(), "rule__RealValue__Group_0__0");
			builder.put(grammarAccess.getUnlimitedNaturalLiteralExpressionAccess().getGroup_1(), "rule__UnlimitedNaturalLiteralExpression__Group_1__0");
			builder.put(grammarAccess.getNamedExpressionMemberAccess().getGroup(), "rule__NamedExpressionMember__Group__0");
			builder.put(grammarAccess.getColonQualifiedNameAccess().getGroup(), "rule__ColonQualifiedName__Group__0");
			builder.put(grammarAccess.getColonQualifiedNameAccess().getGroup_1(), "rule__ColonQualifiedName__Group_1__0");
			builder.put(grammarAccess.getDotQualifiedNameAccess().getGroup(), "rule__DotQualifiedName__Group__0");
			builder.put(grammarAccess.getDotQualifiedNameAccess().getGroup_1(), "rule__DotQualifiedName__Group_1__0");
			builder.put(grammarAccess.getUnitPrefixAccess().getOwnedImportAssignment_0_0(), "rule__UnitPrefix__OwnedImportAssignment_0_0");
			builder.put(grammarAccess.getUnitPrefixAccess().getOwnedMembershipAssignment_0_1(), "rule__UnitPrefix__OwnedMembershipAssignment_0_1");
			builder.put(grammarAccess.getUnitPrefixAccess().getOwnedRelationshipAssignment_1(), "rule__UnitPrefix__OwnedRelationshipAssignment_1");
			builder.put(grammarAccess.getAnnotationAccess().getOwnedRelatedElementAssignment(), "rule__Annotation__OwnedRelatedElementAssignment");
			builder.put(grammarAccess.getCommentAccess().getBodyAssignment(), "rule__Comment__BodyAssignment");
			builder.put(grammarAccess.getPackageImportAccess().getOwnedRelationshipAssignment_0(), "rule__PackageImport__OwnedRelationshipAssignment_0");
			builder.put(grammarAccess.getPackageImportAccess().getVisibilityAssignment_1(), "rule__PackageImport__VisibilityAssignment_1");
			builder.put(grammarAccess.getPackageImportAccess().getImportedPackageAssignment_3_0_0(), "rule__PackageImport__ImportedPackageAssignment_3_0_0");
			builder.put(grammarAccess.getPackageImportAccess().getImportedPackageAssignment_3_1_0(), "rule__PackageImport__ImportedPackageAssignment_3_1_0");
			builder.put(grammarAccess.getPackageImportAccess().getImportedPackageAssignment_3_2_0(), "rule__PackageImport__ImportedPackageAssignment_3_2_0");
			builder.put(grammarAccess.getElementImportAccess().getMemberElementAssignment_2(), "rule__ElementImport__MemberElementAssignment_2");
			builder.put(grammarAccess.getElementImportAccess().getMemberNameAssignment_3_1(), "rule__ElementImport__MemberNameAssignment_3_1");
			builder.put(grammarAccess.getPackageDefinitionAccess().getNameAssignment_1(), "rule__PackageDefinition__NameAssignment_1");
			builder.put(grammarAccess.getPackageDefinitionAccess().getOwnedMembershipAssignment_3_0(), "rule__PackageDefinition__OwnedMembershipAssignment_3_0");
			builder.put(grammarAccess.getPackageDefinitionAccess().getOwnedImportAssignment_3_1(), "rule__PackageDefinition__OwnedImportAssignment_3_1");
			builder.put(grammarAccess.getPackageMemberPrefixAccess().getOwnedRelationshipAssignment_0(), "rule__PackageMemberPrefix__OwnedRelationshipAssignment_0");
			builder.put(grammarAccess.getPackageMemberPrefixAccess().getVisibilityAssignment_1(), "rule__PackageMemberPrefix__VisibilityAssignment_1");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getOwnedMemberElementAssignment_0(), "rule__NonFeatureMemberElement__OwnedMemberElementAssignment_0");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberNameAssignment_1_1(), "rule__NonFeatureMemberElement__MemberNameAssignment_1_1");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberElementAssignment_1_3(), "rule__NonFeatureMemberElement__MemberElementAssignment_1_3");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberNameAssignment_2_1(), "rule__NonFeatureMemberElement__MemberNameAssignment_2_1");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberElementAssignment_2_3(), "rule__NonFeatureMemberElement__MemberElementAssignment_2_3");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberNameAssignment_3_1(), "rule__NonFeatureMemberElement__MemberNameAssignment_3_1");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberElementAssignment_3_3(), "rule__NonFeatureMemberElement__MemberElementAssignment_3_3");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberNameAssignment_4_1(), "rule__NonFeatureMemberElement__MemberNameAssignment_4_1");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberElementAssignment_4_3(), "rule__NonFeatureMemberElement__MemberElementAssignment_4_3");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberNameAssignment_5_1(), "rule__NonFeatureMemberElement__MemberNameAssignment_5_1");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberElementAssignment_5_3(), "rule__NonFeatureMemberElement__MemberElementAssignment_5_3");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberNameAssignment_6_1(), "rule__NonFeatureMemberElement__MemberNameAssignment_6_1");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberElementAssignment_6_3(), "rule__NonFeatureMemberElement__MemberElementAssignment_6_3");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberNameAssignment_7_1(), "rule__NonFeatureMemberElement__MemberNameAssignment_7_1");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberElementAssignment_7_3(), "rule__NonFeatureMemberElement__MemberElementAssignment_7_3");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberElementAssignment_8_1(), "rule__NonFeatureMemberElement__MemberElementAssignment_8_1");
			builder.put(grammarAccess.getNonFeatureMemberElementAccess().getMemberNameAssignment_8_2_1(), "rule__NonFeatureMemberElement__MemberNameAssignment_8_2_1");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getOwnedMemberElementAssignment_0_1(), "rule__FeaturePackageMemberElement__OwnedMemberElementAssignment_0_1");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getOwnedMemberElementAssignment_1_1(), "rule__FeaturePackageMemberElement__OwnedMemberElementAssignment_1_1");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getMemberNameAssignment_2_0_0_1(), "rule__FeaturePackageMemberElement__MemberNameAssignment_2_0_0_1");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getMemberNameAssignment_2_0_1(), "rule__FeaturePackageMemberElement__MemberNameAssignment_2_0_1");
			builder.put(grammarAccess.getFeaturePackageMemberElementAccess().getMemberElementAssignment_2_2(), "rule__FeaturePackageMemberElement__MemberElementAssignment_2_2");
			builder.put(grammarAccess.getCategoryBodyAccess().getOwnedMembershipAssignment_1_1_0(), "rule__CategoryBody__OwnedMembershipAssignment_1_1_0");
			builder.put(grammarAccess.getCategoryBodyAccess().getOwnedImportAssignment_1_1_1(), "rule__CategoryBody__OwnedImportAssignment_1_1_1");
			builder.put(grammarAccess.getFeatureCategoryMemberAccess().getDirectionAssignment_1_1_0(), "rule__FeatureCategoryMember__DirectionAssignment_1_1_0");
			builder.put(grammarAccess.getFeatureCategoryMemberAccess().getOwnedMemberFeatureAssignment_1_1_1(), "rule__FeatureCategoryMember__OwnedMemberFeatureAssignment_1_1_1");
			builder.put(grammarAccess.getFeatureCategoryMemberAccess().getDirectionAssignment_1_2_0(), "rule__FeatureCategoryMember__DirectionAssignment_1_2_0");
			builder.put(grammarAccess.getFeatureCategoryMemberAccess().getMemberNameAssignment_1_2_1(), "rule__FeatureCategoryMember__MemberNameAssignment_1_2_1");
			builder.put(grammarAccess.getFeatureCategoryMemberAccess().getMemberFeatureAssignment_1_2_3(), "rule__FeatureCategoryMember__MemberFeatureAssignment_1_2_3");
			builder.put(grammarAccess.getCategoryMemberPrefixAccess().getOwnedRelationshipAssignment_0(), "rule__CategoryMemberPrefix__OwnedRelationshipAssignment_0");
			builder.put(grammarAccess.getCategoryMemberPrefixAccess().getVisibilityAssignment_1(), "rule__CategoryMemberPrefix__VisibilityAssignment_1");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getIsPartAssignment_0_0_1(), "rule__FeatureMemberElement__IsPartAssignment_0_0_1");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getIsPortAssignment_0_0_2(), "rule__FeatureMemberElement__IsPortAssignment_0_0_2");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getDirectionAssignment_0_1(), "rule__FeatureMemberElement__DirectionAssignment_0_1");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getOwnedMemberFeatureAssignment_0_2_0(), "rule__FeatureMemberElement__OwnedMemberFeatureAssignment_0_2_0");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getMemberNameAssignment_0_2_1_0(), "rule__FeatureMemberElement__MemberNameAssignment_0_2_1_0");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getMemberFeatureAssignment_0_2_1_2(), "rule__FeatureMemberElement__MemberFeatureAssignment_0_2_1_2");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getOwnedMemberFeatureAssignment_1_1_0(), "rule__FeatureMemberElement__OwnedMemberFeatureAssignment_1_1_0");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getMemberNameAssignment_1_1_1_0(), "rule__FeatureMemberElement__MemberNameAssignment_1_1_1_0");
			builder.put(grammarAccess.getFeatureMemberElementAccess().getMemberFeatureAssignment_1_1_1_2(), "rule__FeatureMemberElement__MemberFeatureAssignment_1_1_1_2");
			builder.put(grammarAccess.getClassDeclarationAccess().getIsAbstractAssignment_0(), "rule__ClassDeclaration__IsAbstractAssignment_0");
			builder.put(grammarAccess.getClassDeclarationCompletionAccess().getNameAssignment_0(), "rule__ClassDeclarationCompletion__NameAssignment_0");
			builder.put(grammarAccess.getSpecializationListAccess().getOwnedRelationshipAssignment_1(), "rule__SpecializationList__OwnedRelationshipAssignment_1");
			builder.put(grammarAccess.getSpecializationListAccess().getOwnedRelationshipAssignment_2_1(), "rule__SpecializationList__OwnedRelationshipAssignment_2_1");
			builder.put(grammarAccess.getSuperclassingAccess().getSuperclassAssignment(), "rule__Superclassing__SuperclassAssignment");
			builder.put(grammarAccess.getObjectClassDeclarationAccess().getIsAbstractAssignment_0(), "rule__ObjectClassDeclaration__IsAbstractAssignment_0");
			builder.put(grammarAccess.getValueClassDeclarationAccess().getIsAbstractAssignment_0(), "rule__ValueClassDeclaration__IsAbstractAssignment_0");
			builder.put(grammarAccess.getAssociationDeclarationAccess().getIsAbstractAssignment_0(), "rule__AssociationDeclaration__IsAbstractAssignment_0");
			builder.put(grammarAccess.getAssociationBodyAccess().getOwnedMembershipAssignment_1_1_0(), "rule__AssociationBody__OwnedMembershipAssignment_1_1_0");
			builder.put(grammarAccess.getAssociationBodyAccess().getOwnedImportAssignment_1_1_1(), "rule__AssociationBody__OwnedImportAssignment_1_1_1");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getIsPartAssignment_1_0_1_0(), "rule__AssociationEndFeatureMember__IsPartAssignment_1_0_1_0");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getIsPortAssignment_1_0_1_1(), "rule__AssociationEndFeatureMember__IsPortAssignment_1_0_1_1");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getDirectionAssignment_1_0_2(), "rule__AssociationEndFeatureMember__DirectionAssignment_1_0_2");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getOwnedMemberFeatureAssignment_1_0_3(), "rule__AssociationEndFeatureMember__OwnedMemberFeatureAssignment_1_0_3");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getIsPartAssignment_1_1_1(), "rule__AssociationEndFeatureMember__IsPartAssignment_1_1_1");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getMemberNameAssignment_1_1_2(), "rule__AssociationEndFeatureMember__MemberNameAssignment_1_1_2");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getMemberFeatureAssignment_1_1_4(), "rule__AssociationEndFeatureMember__MemberFeatureAssignment_1_1_4");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getDirectionAssignment_1_2_0(), "rule__AssociationEndFeatureMember__DirectionAssignment_1_2_0");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getOwnedMemberFeatureAssignment_1_2_1(), "rule__AssociationEndFeatureMember__OwnedMemberFeatureAssignment_1_2_1");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getMemberNameAssignment_1_3_0(), "rule__AssociationEndFeatureMember__MemberNameAssignment_1_3_0");
			builder.put(grammarAccess.getAssociationEndFeatureMemberAccess().getMemberFeatureAssignment_1_3_2(), "rule__AssociationEndFeatureMember__MemberFeatureAssignment_1_3_2");
			builder.put(grammarAccess.getBehaviorDeclarationAccess().getIsAbstractAssignment_0(), "rule__BehaviorDeclaration__IsAbstractAssignment_0");
			builder.put(grammarAccess.getBehaviorDeclarationAccess().getNameAssignment_2(), "rule__BehaviorDeclaration__NameAssignment_2");
			builder.put(grammarAccess.getParameterListAccess().getOwnedMembershipAssignment_1_0(), "rule__ParameterList__OwnedMembershipAssignment_1_0");
			builder.put(grammarAccess.getParameterListAccess().getOwnedMembershipAssignment_1_1_1(), "rule__ParameterList__OwnedMembershipAssignment_1_1_1");
			builder.put(grammarAccess.getParameterMemberAccess().getDirectionAssignment_0(), "rule__ParameterMember__DirectionAssignment_0");
			builder.put(grammarAccess.getParameterMemberAccess().getMemberNameAssignment_1(), "rule__ParameterMember__MemberNameAssignment_1");
			builder.put(grammarAccess.getParameterMemberAccess().getOwnedMemberFeatureAssignment_2(), "rule__ParameterMember__OwnedMemberFeatureAssignment_2");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getIsAbstractAssignment_0(), "rule__FunctionDeclaration__IsAbstractAssignment_0");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getNameAssignment_2(), "rule__FunctionDeclaration__NameAssignment_2");
			builder.put(grammarAccess.getReturnParameterPartAccess().getOwnedMembershipAssignment(), "rule__ReturnParameterPart__OwnedMembershipAssignment");
			builder.put(grammarAccess.getReturnParameterMemberAccess().getMemberNameAssignment_0(), "rule__ReturnParameterMember__MemberNameAssignment_0");
			builder.put(grammarAccess.getReturnParameterMemberAccess().getOwnedMemberFeatureAssignment_1(), "rule__ReturnParameterMember__OwnedMemberFeatureAssignment_1");
			builder.put(grammarAccess.getUnnamedFeatureDefinitionAccess().getOwnedRelationshipAssignment_1(), "rule__UnnamedFeatureDefinition__OwnedRelationshipAssignment_1");
			builder.put(grammarAccess.getFeatureDeclarationAccess().getNameAssignment_0(), "rule__FeatureDeclaration__NameAssignment_0");
			builder.put(grammarAccess.getFeatureCompletionAccess().getValuationAssignment_0_1(), "rule__FeatureCompletion__ValuationAssignment_0_1");
			builder.put(grammarAccess.getFeatureValueAccess().getValueAssignment(), "rule__FeatureValue__ValueAssignment");
			builder.put(grammarAccess.getTypePartAccess().getIsCompositeAssignment_0_1(), "rule__TypePart__IsCompositeAssignment_0_1");
			builder.put(grammarAccess.getTypePartAccess().getOwnedRelationshipAssignment_0_2_0(), "rule__TypePart__OwnedRelationshipAssignment_0_2_0");
			builder.put(grammarAccess.getTypePartAccess().getMultiplicityAssignment_1(), "rule__TypePart__MultiplicityAssignment_1");
			builder.put(grammarAccess.getTypePartAccess().getIsOrderedAssignment_2_0(), "rule__TypePart__IsOrderedAssignment_2_0");
			builder.put(grammarAccess.getTypePartAccess().getIsNonuniqueAssignment_2_1(), "rule__TypePart__IsNonuniqueAssignment_2_1");
			builder.put(grammarAccess.getFeatureTypingAccess().getTypeAssignment(), "rule__FeatureTyping__TypeAssignment");
			builder.put(grammarAccess.getMultiplicityAccess().getLowerAssignment_1_0(), "rule__Multiplicity__LowerAssignment_1_0");
			builder.put(grammarAccess.getMultiplicityAccess().getUpperAssignment_2(), "rule__Multiplicity__UpperAssignment_2");
			builder.put(grammarAccess.getSubsettingPartAccess().getOwnedRelationshipAssignment_0_1_1(), "rule__SubsettingPart__OwnedRelationshipAssignment_0_1_1");
			builder.put(grammarAccess.getSubsettingPartAccess().getOwnedRelationshipAssignment_1_1_1(), "rule__SubsettingPart__OwnedRelationshipAssignment_1_1_1");
			builder.put(grammarAccess.getSubsetsAccess().getOwnedRelationshipAssignment_1(), "rule__Subsets__OwnedRelationshipAssignment_1");
			builder.put(grammarAccess.getSubsetAccess().getSubsettedFeatureAssignment(), "rule__Subset__SubsettedFeatureAssignment");
			builder.put(grammarAccess.getRedefinesAccess().getOwnedRelationshipAssignment_1(), "rule__Redefines__OwnedRelationshipAssignment_1");
			builder.put(grammarAccess.getRedefinitionAccess().getRedefinedFeatureAssignment(), "rule__Redefinition__RedefinedFeatureAssignment");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getNameAssignment_0_0_0_0(), "rule__ConnectorDefinition__NameAssignment_0_0_0_0");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getOwnedRelationshipAssignment_0_0_0_1_1(), "rule__ConnectorDefinition__OwnedRelationshipAssignment_0_0_0_1_1");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getConnectorEndAssignment_0_0_1(), "rule__ConnectorDefinition__ConnectorEndAssignment_0_0_1");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getConnectorEndAssignment_0_0_3(), "rule__ConnectorDefinition__ConnectorEndAssignment_0_0_3");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getNameAssignment_0_1_0(), "rule__ConnectorDefinition__NameAssignment_0_1_0");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getOwnedRelationshipAssignment_0_1_1_1(), "rule__ConnectorDefinition__OwnedRelationshipAssignment_0_1_1_1");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getConnectorEndAssignment_0_1_3(), "rule__ConnectorDefinition__ConnectorEndAssignment_0_1_3");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getConnectorEndAssignment_0_1_5(), "rule__ConnectorDefinition__ConnectorEndAssignment_0_1_5");
			builder.put(grammarAccess.getConnectorDefinitionAccess().getConnectorEndAssignment_0_1_6_1(), "rule__ConnectorDefinition__ConnectorEndAssignment_0_1_6_1");
			builder.put(grammarAccess.getConnectorTypingAccess().getTypeAssignment(), "rule__ConnectorTyping__TypeAssignment");
			builder.put(grammarAccess.getConnectorEndAccess().getEndAssignment_0_0_0(), "rule__ConnectorEnd__EndAssignment_0_0_0");
			builder.put(grammarAccess.getConnectorEndAccess().getFeatureAssignment_0_1(), "rule__ConnectorEnd__FeatureAssignment_0_1");
			builder.put(grammarAccess.getConnectorEndAccess().getMultiplicityAssignment_0_2(), "rule__ConnectorEnd__MultiplicityAssignment_0_2");
			builder.put(grammarAccess.getConnectorEndAccess().getEndAssignment_1_0_0(), "rule__ConnectorEnd__EndAssignment_1_0_0");
			builder.put(grammarAccess.getConnectorEndAccess().getMultiplicityAssignment_1_0_1(), "rule__ConnectorEnd__MultiplicityAssignment_1_0_1");
			builder.put(grammarAccess.getConnectorEndAccess().getFeatureAssignment_1_1(), "rule__ConnectorEnd__FeatureAssignment_1_1");
			builder.put(grammarAccess.getBinaryExpressionAccess().getOperatorAssignment_1_1_0_0(), "rule__BinaryExpression__OperatorAssignment_1_1_0_0");
			builder.put(grammarAccess.getBinaryExpressionAccess().getOperandAssignment_1_1_0_1(), "rule__BinaryExpression__OperandAssignment_1_1_0_1");
			builder.put(grammarAccess.getBinaryExpressionAccess().getOperatorAssignment_1_1_1_0(), "rule__BinaryExpression__OperatorAssignment_1_1_1_0");
			builder.put(grammarAccess.getBinaryExpressionAccess().getOperandAssignment_1_1_1_2(), "rule__BinaryExpression__OperandAssignment_1_1_1_2");
			builder.put(grammarAccess.getUnaryExpressionAccess().getOperatorAssignment_1_1(), "rule__UnaryExpression__OperatorAssignment_1_1");
			builder.put(grammarAccess.getUnaryExpressionAccess().getOperandAssignment_1_2(), "rule__UnaryExpression__OperandAssignment_1_2");
			builder.put(grammarAccess.getSequenceAccessExpressionAccess().getOperatorAssignment_1_1(), "rule__SequenceAccessExpression__OperatorAssignment_1_1");
			builder.put(grammarAccess.getSequenceAccessExpressionAccess().getOperandAssignment_1_2(), "rule__SequenceAccessExpression__OperandAssignment_1_2");
			builder.put(grammarAccess.getNameExpressionAccess().getOwnedMembershipAssignment(), "rule__NameExpression__OwnedMembershipAssignment");
			builder.put(grammarAccess.getInvocationExpressionAccess().getOwnedRelationshipAssignment_0(), "rule__InvocationExpression__OwnedRelationshipAssignment_0");
			builder.put(grammarAccess.getPositionalTupleAccess().getOwnedMembershipAssignment_0(), "rule__PositionalTuple__OwnedMembershipAssignment_0");
			builder.put(grammarAccess.getPositionalTupleAccess().getOwnedMembershipAssignment_1_1(), "rule__PositionalTuple__OwnedMembershipAssignment_1_1");
			builder.put(grammarAccess.getNamedTupleAccess().getOwnedMembershipAssignment_0(), "rule__NamedTuple__OwnedMembershipAssignment_0");
			builder.put(grammarAccess.getNamedTupleAccess().getOwnedMembershipAssignment_1_1(), "rule__NamedTuple__OwnedMembershipAssignment_1_1");
			builder.put(grammarAccess.getSequenceConstructionExpressionAccess().getElementAssignment_2_0(), "rule__SequenceConstructionExpression__ElementAssignment_2_0");
			builder.put(grammarAccess.getSequenceConstructionExpressionAccess().getElementAssignment_2_1_1(), "rule__SequenceConstructionExpression__ElementAssignment_2_1_1");
			builder.put(grammarAccess.getBooleanLiteralExpressionAccess().getValueAssignment(), "rule__BooleanLiteralExpression__ValueAssignment");
			builder.put(grammarAccess.getStringLiteralExpressionAccess().getValueAssignment(), "rule__StringLiteralExpression__ValueAssignment");
			builder.put(grammarAccess.getRealLiteralExpressionAccess().getValueAssignment(), "rule__RealLiteralExpression__ValueAssignment");
			builder.put(grammarAccess.getNaturalLiteralExpressionAccess().getValueAssignment(), "rule__NaturalLiteralExpression__ValueAssignment");
			builder.put(grammarAccess.getExpressionMemberAccess().getOwnedMemberFeatureAssignment(), "rule__ExpressionMember__OwnedMemberFeatureAssignment");
			builder.put(grammarAccess.getNamedExpressionMemberAccess().getMemberNameAssignment_0(), "rule__NamedExpressionMember__MemberNameAssignment_0");
			builder.put(grammarAccess.getNamedExpressionMemberAccess().getOwnedMemberFeatureAssignment_2(), "rule__NamedExpressionMember__OwnedMemberFeatureAssignment_2");
			builder.put(grammarAccess.getNamedFeatureReferenceAccess().getMemberFeatureAssignment(), "rule__NamedFeatureReference__MemberFeatureAssignment");
			builder.put(grammarAccess.getTypePartAccess().getUnorderedGroup_2(), "rule__TypePart__UnorderedGroup_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AlfGrammarAccess grammarAccess;

	@Override
	protected InternalAlfParser createParser() {
		InternalAlfParser result = new InternalAlfParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AlfGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AlfGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
