= Jupyter SysML Kernel

A http://jupyter.org/[Jupyter] kernel for executing SysML v2 models. The kernel executes models via the new SysML textual language. Some of the additional commands should be supported as needed via a syntax similar to the IPython magics.

Built on top of https://github.com/SpencerPark/jupyter-jvm-basekernel[jupyter-jvm-basekernel].

== Requirements

1.  http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java >= 17].
2.  Some Jupyter-like environment to use the kernel in. A non-exhaustive list of options:
    *   http://jupyter.org/install[Jupyter]
    *   http://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html[JupyterLab]
    *   https://nteract.io/desktop[nteract]


== Installing

After meeting the <<Requirements>>, the kernel can be installed locally. Any time you wish to remove a kernel you may use `jupyter kernelspec remove sysml`. If you have installed the kernel to multiple directories, this command may need to be run multiple times as it might only remove 1 installation at a time.

=== Build and install
For quick local deployment use the `installKernel.sh` or `installKernel.bat` script depending on your system. These scripts will build the kernel and install it to your local Jupyter installation.

**Note:** Local Maven install of the parent project (`org.omg.sysml`) and all submodules is required to run the scripts. You can go to the root project and call `./mvnw install`

=== Install pre-built binary

Get the latest _release_ of the software with no compilation needed. See <<Install from source>> for building the latest commit.

**Note:** if you have an old installation or a debug one from running `gradlew installKernel` it is suggested that it is first removed via `jupyter kernelspec remove sysml`.

1.  Download the release from the [releases tab](.). A prepackaged distribution will be in an artifact named `sysml-jupyter-kernel-$version.zip`.

2.  Unzip it into a temporary location. It should have at least the `install.py` and `sysml` folder extracted in there.

3.  Run the installer with the same python command used to install jupyter. The installer is a python script and has the same options as `jupyter kernelspec install` but additionally supports configuring some of the kernel properties mentioned further below in the README.
+
[source,shell]
----
# Pass the -h option to see the help page
> python3 install.py -h

# Otherwise a common install command is
> python3 install.py --sys-prefix
----

4.  Check that it installed with `jupyter kernelspec list` which should contain `sysml`.

=== Configuring

Configuring the kernel can be done via environment variables. These can be set on the system or inside the `kernel.json`. The configuration can be done at install time, which may be repeated as often as desired. The parameters are listed with `python3 install.py -h` as well as below in the list of options.

==== List of options

[cols="1,1,1,1"]
|===
| Environment variable | Parameter name | Default | Description

| `ISYSML_LIBRARY_PATH` | `library-path` | `""` | A file path separator delimited list of library path entries that should be available to the user code. **Important:** no matter what OS, this should use forward slash "/" as the file separator.
| `ISYSML_API_BASE_PATH` | `api-base-path` | `""` | The base path for the API that the model is published to using the %publish magic command.
| `ISYSML_GRAPHVIZ_PATH` | `graphviz-path` | `""` | The path to the Graphviz dot executable that is used for the %viz magic command.
|===

==== Changing VM options

The kernel VM parameters must currently be assigned in the `kernel.json` by adding/editing a JSON dictionary at the `env` key and changing the `argv` list. To find where the kernel is installed run

[source,shell]
----
> jupyter kernelspec list
Available kernels:
  sysml          .../kernels/sysml
  python3        .../kernels/python3
----

and the `kernel.json` file will be in the given directory.

For example to set the heap size to `128m`:

[source,diff]
----
{
- "argv": [ "java", "-jar", "{connection_file}"],
+ "argv": [ "java", "-Xmx128m", "-jar", "{connection_file}"],
  "display_name": "SysML",
  "language": "sysml",
  "interrupt_mode": "message",
  "env": {
  }
}
----

=== Run

This is where the documentation diverges as each environment has its own way of selecting a kernel. To test from command line with Jupyter's console application run:

[source,bash]
----
jupyter console --kernel=sysml
----

Then at the prompt try:

[source]
----
In [1]: package test{}
----
