/*
 * generated by Xtext 2.18.0
 */
package org.omg.kerml.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.omg.kerml.xtext.services.KerMLGrammarAccess;

@SuppressWarnings("all")
public class KerMLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected KerMLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_BaseExpression_LeftParenthesisKeyword_6_0_a;
	protected AbstractElementAlias match_BaseExpression_LeftParenthesisKeyword_6_0_p;
	protected AbstractElementAlias match_BaseExpression_QueryHeadExpression___LeftParenthesisKeyword_6_0_p_FullStopSolidusKeyword_0_q__q;
	protected AbstractElementAlias match_BehaviorBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_2__;
	protected AbstractElementAlias match_Documentation_CommentKeyword_0_0_q;
	protected AbstractElementAlias match_EndFeatureMember_EndKeyword_1_0_0_or___AbstractKeyword_1_1_0_EndKeyword_1_1_1__;
	protected AbstractElementAlias match_ExpressionDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1;
	protected AbstractElementAlias match_FeatureDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1;
	protected AbstractElementAlias match_FeatureMemberElement_FeatureKeyword_0_0_q;
	protected AbstractElementAlias match_FeatureMember_AbstractKeyword_1_1_0_q;
	protected AbstractElementAlias match_FunctionBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_3__;
	protected AbstractElementAlias match_PackageFeatureMemberElement_FeatureKeyword_0_0_q;
	protected AbstractElementAlias match_PackageFeatureMemberElement_FeatureKeyword_2_1_q;
	protected AbstractElementAlias match_PackageImport_ColonColonKeyword_3_0_1_0_or_FullStopKeyword_3_0_1_1;
	protected AbstractElementAlias match_QueryHeadExpression_FullStopSolidusKeyword_0_q;
	protected AbstractElementAlias match_Redefines_ColonGreaterThanSignGreaterThanSignKeyword_0_0_or_RedefinesKeyword_0_1;
	protected AbstractElementAlias match_SpecializationList_ColonGreaterThanSignKeyword_0_0_or_SpecializesKeyword_0_1;
	protected AbstractElementAlias match_StepDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1;
	protected AbstractElementAlias match_Subsets_ColonGreaterThanSignKeyword_0_0_or_SubsetsKeyword_0_1;
	protected AbstractElementAlias match_TypeBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_2__;
	protected AbstractElementAlias match_TypePart___ColonKeyword_0_0_AnyKeyword_0_2_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (KerMLGrammarAccess) access;
		match_BaseExpression_LeftParenthesisKeyword_6_0_a = new TokenAlias(true, true, grammarAccess.getBaseExpressionAccess().getLeftParenthesisKeyword_6_0());
		match_BaseExpression_LeftParenthesisKeyword_6_0_p = new TokenAlias(true, false, grammarAccess.getBaseExpressionAccess().getLeftParenthesisKeyword_6_0());
		match_BaseExpression_QueryHeadExpression___LeftParenthesisKeyword_6_0_p_FullStopSolidusKeyword_0_q__q = new GroupAlias(false, true, new TokenAlias(true, false, grammarAccess.getBaseExpressionAccess().getLeftParenthesisKeyword_6_0()), new TokenAlias(false, true, grammarAccess.getQueryHeadExpressionAccess().getFullStopSolidusKeyword_0()));
		match_BehaviorBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_2__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getBehaviorBodyAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getBehaviorBodyAccess().getRightCurlyBracketKeyword_1_2())), new TokenAlias(false, false, grammarAccess.getBehaviorBodyAccess().getSemicolonKeyword_0()));
		match_Documentation_CommentKeyword_0_0_q = new TokenAlias(false, true, grammarAccess.getDocumentationAccess().getCommentKeyword_0_0());
		match_EndFeatureMember_EndKeyword_1_0_0_or___AbstractKeyword_1_1_0_EndKeyword_1_1_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEndFeatureMemberAccess().getAbstractKeyword_1_1_0()), new TokenAlias(false, false, grammarAccess.getEndFeatureMemberAccess().getEndKeyword_1_1_1())), new TokenAlias(false, false, grammarAccess.getEndFeatureMemberAccess().getEndKeyword_1_0_0()));
		match_ExpressionDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getExpressionDeclarationAccess().getColonGreaterThanSignGreaterThanSignKeyword_2_0_0()), new TokenAlias(false, false, grammarAccess.getExpressionDeclarationAccess().getRedefinesKeyword_2_0_1()));
		match_FeatureDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getFeatureDeclarationAccess().getColonGreaterThanSignGreaterThanSignKeyword_2_0_0()), new TokenAlias(false, false, grammarAccess.getFeatureDeclarationAccess().getRedefinesKeyword_2_0_1()));
		match_FeatureMemberElement_FeatureKeyword_0_0_q = new TokenAlias(false, true, grammarAccess.getFeatureMemberElementAccess().getFeatureKeyword_0_0());
		match_FeatureMember_AbstractKeyword_1_1_0_q = new TokenAlias(false, true, grammarAccess.getFeatureMemberAccess().getAbstractKeyword_1_1_0());
		match_FunctionBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getFunctionBodyAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getFunctionBodyAccess().getRightCurlyBracketKeyword_1_3())), new TokenAlias(false, false, grammarAccess.getFunctionBodyAccess().getSemicolonKeyword_0()));
		match_PackageFeatureMemberElement_FeatureKeyword_0_0_q = new TokenAlias(false, true, grammarAccess.getPackageFeatureMemberElementAccess().getFeatureKeyword_0_0());
		match_PackageFeatureMemberElement_FeatureKeyword_2_1_q = new TokenAlias(false, true, grammarAccess.getPackageFeatureMemberElementAccess().getFeatureKeyword_2_1());
		match_PackageImport_ColonColonKeyword_3_0_1_0_or_FullStopKeyword_3_0_1_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getPackageImportAccess().getColonColonKeyword_3_0_1_0()), new TokenAlias(false, false, grammarAccess.getPackageImportAccess().getFullStopKeyword_3_0_1_1()));
		match_QueryHeadExpression_FullStopSolidusKeyword_0_q = new TokenAlias(false, true, grammarAccess.getQueryHeadExpressionAccess().getFullStopSolidusKeyword_0());
		match_Redefines_ColonGreaterThanSignGreaterThanSignKeyword_0_0_or_RedefinesKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getRedefinesAccess().getColonGreaterThanSignGreaterThanSignKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getRedefinesAccess().getRedefinesKeyword_0_1()));
		match_SpecializationList_ColonGreaterThanSignKeyword_0_0_or_SpecializesKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getSpecializationListAccess().getColonGreaterThanSignKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getSpecializationListAccess().getSpecializesKeyword_0_1()));
		match_StepDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getStepDeclarationAccess().getColonGreaterThanSignGreaterThanSignKeyword_2_0_0()), new TokenAlias(false, false, grammarAccess.getStepDeclarationAccess().getRedefinesKeyword_2_0_1()));
		match_Subsets_ColonGreaterThanSignKeyword_0_0_or_SubsetsKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getSubsetsAccess().getColonGreaterThanSignKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getSubsetsAccess().getSubsetsKeyword_0_1()));
		match_TypeBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_2__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getTypeBodyAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getTypeBodyAccess().getRightCurlyBracketKeyword_1_2())), new TokenAlias(false, false, grammarAccess.getTypeBodyAccess().getSemicolonKeyword_0()));
		match_TypePart___ColonKeyword_0_0_AnyKeyword_0_2_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getTypePartAccess().getColonKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getTypePartAccess().getAnyKeyword_0_2_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_BaseExpression_LeftParenthesisKeyword_6_0_a.equals(syntax))
				emit_BaseExpression_LeftParenthesisKeyword_6_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_BaseExpression_LeftParenthesisKeyword_6_0_p.equals(syntax))
				emit_BaseExpression_LeftParenthesisKeyword_6_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_BaseExpression_QueryHeadExpression___LeftParenthesisKeyword_6_0_p_FullStopSolidusKeyword_0_q__q.equals(syntax))
				emit_BaseExpression_QueryHeadExpression___LeftParenthesisKeyword_6_0_p_FullStopSolidusKeyword_0_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_BehaviorBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_2__.equals(syntax))
				emit_BehaviorBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_2__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Documentation_CommentKeyword_0_0_q.equals(syntax))
				emit_Documentation_CommentKeyword_0_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EndFeatureMember_EndKeyword_1_0_0_or___AbstractKeyword_1_1_0_EndKeyword_1_1_1__.equals(syntax))
				emit_EndFeatureMember_EndKeyword_1_0_0_or___AbstractKeyword_1_1_0_EndKeyword_1_1_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ExpressionDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1.equals(syntax))
				emit_ExpressionDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FeatureDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1.equals(syntax))
				emit_FeatureDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FeatureMemberElement_FeatureKeyword_0_0_q.equals(syntax))
				emit_FeatureMemberElement_FeatureKeyword_0_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FeatureMember_AbstractKeyword_1_1_0_q.equals(syntax))
				emit_FeatureMember_AbstractKeyword_1_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FunctionBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_3__.equals(syntax))
				emit_FunctionBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PackageFeatureMemberElement_FeatureKeyword_0_0_q.equals(syntax))
				emit_PackageFeatureMemberElement_FeatureKeyword_0_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PackageFeatureMemberElement_FeatureKeyword_2_1_q.equals(syntax))
				emit_PackageFeatureMemberElement_FeatureKeyword_2_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PackageImport_ColonColonKeyword_3_0_1_0_or_FullStopKeyword_3_0_1_1.equals(syntax))
				emit_PackageImport_ColonColonKeyword_3_0_1_0_or_FullStopKeyword_3_0_1_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_QueryHeadExpression_FullStopSolidusKeyword_0_q.equals(syntax))
				emit_QueryHeadExpression_FullStopSolidusKeyword_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Redefines_ColonGreaterThanSignGreaterThanSignKeyword_0_0_or_RedefinesKeyword_0_1.equals(syntax))
				emit_Redefines_ColonGreaterThanSignGreaterThanSignKeyword_0_0_or_RedefinesKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SpecializationList_ColonGreaterThanSignKeyword_0_0_or_SpecializesKeyword_0_1.equals(syntax))
				emit_SpecializationList_ColonGreaterThanSignKeyword_0_0_or_SpecializesKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StepDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1.equals(syntax))
				emit_StepDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Subsets_ColonGreaterThanSignKeyword_0_0_or_SubsetsKeyword_0_1.equals(syntax))
				emit_Subsets_ColonGreaterThanSignKeyword_0_0_or_SubsetsKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_TypeBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_2__.equals(syntax))
				emit_TypeBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_2__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_TypePart___ColonKeyword_0_0_AnyKeyword_0_2_1__q.equals(syntax))
				emit_TypePart___ColonKeyword_0_0_AnyKeyword_0_2_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '*' (rule start)
	 *     (rule start) (ambiguity) './'? ownedRelationship+=FeatureReference
	 *     (rule start) (ambiguity) 'null' (rule start)
	 *     (rule start) (ambiguity) '{' '}' (rule start)
	 *     (rule start) (ambiguity) '{' element+=Expression
	 *     (rule start) (ambiguity) operator=UnaryOperator
	 *     (rule start) (ambiguity) ownedRelationship+=FeatureTyping
	 *     (rule start) (ambiguity) ownedRelationship+=TypeReferenceMember
	 *     (rule start) (ambiguity) value=BOOLEAN_VALUE
	 *     (rule start) (ambiguity) value=NATURAL_VALUE
	 *     (rule start) (ambiguity) value=RealValue
	 *     (rule start) (ambiguity) value=STRING_VALUE
	 *     (rule start) (ambiguity) {OperatorExpression.operand+=}
	 *     (rule start) (ambiguity) {QueryPathStepExpression.operand+=}
	 *     (rule start) (ambiguity) {QueryQualifierExpression.operand+=}
	 */
	protected void emit_BaseExpression_LeftParenthesisKeyword_6_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) operator=UnaryOperator
	 *     (rule start) (ambiguity) {OperatorExpression.operand+=}
	 *     (rule start) (ambiguity) {QueryPathStepExpression.operand+=}
	 *     (rule start) (ambiguity) {QueryQualifierExpression.operand+=}
	 */
	protected void emit_BaseExpression_LeftParenthesisKeyword_6_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('('+ './'?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) ownedRelationship+=FeatureReference
	 */
	protected void emit_BaseExpression_QueryHeadExpression___LeftParenthesisKeyword_6_0_p_FullStopSolidusKeyword_0_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';' | ('{' '}')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     isNonunique?='nonunique' (ambiguity) (rule end)
	 *     isOrdered?='ordered' (ambiguity) (rule end)
	 *     isSufficient?='all' 'any' (ambiguity) (rule end)
	 *     name=Name (ambiguity) (rule end)
	 *     ownedRelationship+=FeatureTyping (ambiguity) (rule end)
	 *     ownedRelationship+=FeatureValue (ambiguity) (rule end)
	 *     ownedRelationship+=Multiplicity (ambiguity) (rule end)
	 *     ownedRelationship+=ParameterMember ')' (ambiguity) (rule end)
	 *     ownedRelationship+=Redefinition (ambiguity) (rule end)
	 *     ownedRelationship+=Subset (ambiguity) (rule end)
	 *     ownedRelationship+=Superclassing (ambiguity) (rule end)
	 */
	protected void emit_BehaviorBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_2__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'comment'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) body=DOCUMENTATION_COMMENT
	 */
	protected void emit_Documentation_CommentKeyword_0_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'end' | ('abstract' 'end')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'binding' 'is' memberFeature=[BindingConnector|QualifiedName]
	 *     (rule start) (ambiguity) 'binding' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'binding' memberName=Name
	 *     (rule start) (ambiguity) 'binding' ownedRelatedElement+=AbstractBindingConnector
	 *     (rule start) (ambiguity) 'binding' ownedRelatedElement+=BindingConnector
	 *     (rule start) (ambiguity) 'connector' 'is' memberFeature=[Connector|QualifiedName]
	 *     (rule start) (ambiguity) 'connector' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'connector' memberName=Name
	 *     (rule start) (ambiguity) 'connector' ownedRelatedElement+=AbstractConnector
	 *     (rule start) (ambiguity) 'connector' ownedRelatedElement+=Connector
	 *     (rule start) (ambiguity) 'expr' 'is' memberFeature=[Expression|QualifiedName]
	 *     (rule start) (ambiguity) 'expr' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'expr' memberName=Name
	 *     (rule start) (ambiguity) 'expr' ownedRelatedElement+=AbstractBlockExpression
	 *     (rule start) (ambiguity) 'expr' ownedRelatedElement+=BlockExpression
	 *     (rule start) (ambiguity) 'feature' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'feature' ownedRelatedElement+=AbstractFeature
	 *     (rule start) (ambiguity) 'feature'? 'is' memberFeature=[Feature|QualifiedName]
	 *     (rule start) (ambiguity) 'feature'? direction=FeatureDirection
	 *     (rule start) (ambiguity) 'feature'? memberName=Name
	 *     (rule start) (ambiguity) 'feature'? ownedRelatedElement+=Feature
	 *     (rule start) (ambiguity) 'flow' 'is' memberFeature=[SuccessionItemFlow|QualifiedName]
	 *     (rule start) (ambiguity) 'flow' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'flow' memberName=Name
	 *     (rule start) (ambiguity) 'flow' ownedRelatedElement+=AbstractSuccessionItemFlow
	 *     (rule start) (ambiguity) 'flow' ownedRelatedElement+=SuccessionItemFlow
	 *     (rule start) (ambiguity) 'step' 'is' memberFeature=[Step|QualifiedName]
	 *     (rule start) (ambiguity) 'step' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'step' memberName=Name
	 *     (rule start) (ambiguity) 'step' ownedRelatedElement+=AbstractStep
	 *     (rule start) (ambiguity) 'step' ownedRelatedElement+=Step
	 *     (rule start) (ambiguity) 'stream' 'is' memberFeature=[ItemFlow|QualifiedName]
	 *     (rule start) (ambiguity) 'stream' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'stream' memberName=Name
	 *     (rule start) (ambiguity) 'stream' ownedRelatedElement+=AbstractItemFlow
	 *     (rule start) (ambiguity) 'stream' ownedRelatedElement+=ItemFlow
	 *     (rule start) (ambiguity) 'succession' 'is' memberFeature=[Succession|QualifiedName]
	 *     (rule start) (ambiguity) 'succession' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'succession' memberName=Name
	 *     (rule start) (ambiguity) 'succession' ownedRelatedElement+=AbstractSuccession
	 *     (rule start) (ambiguity) 'succession' ownedRelatedElement+=Succession
	 *     (rule start) (ambiguity) isComposite?='composite'
	 *     (rule start) (ambiguity) isPort?='port'
	 *     (rule start) (ambiguity) isPortion?='portion'
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'binding' 'is' memberFeature=[BindingConnector|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'binding' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'binding' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'binding' ownedRelatedElement+=AbstractBindingConnector
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'binding' ownedRelatedElement+=BindingConnector
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'connector' 'is' memberFeature=[Connector|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'connector' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'connector' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'connector' ownedRelatedElement+=AbstractConnector
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'connector' ownedRelatedElement+=Connector
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'expr' 'is' memberFeature=[Expression|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'expr' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'expr' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'expr' ownedRelatedElement+=AbstractBlockExpression
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'expr' ownedRelatedElement+=BlockExpression
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature' ownedRelatedElement+=AbstractFeature
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature'? 'is' memberFeature=[Feature|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature'? direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature'? memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature'? ownedRelatedElement+=Feature
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'flow' 'is' memberFeature=[SuccessionItemFlow|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'flow' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'flow' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'flow' ownedRelatedElement+=AbstractSuccessionItemFlow
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'flow' ownedRelatedElement+=SuccessionItemFlow
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'step' 'is' memberFeature=[Step|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'step' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'step' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'step' ownedRelatedElement+=AbstractStep
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'step' ownedRelatedElement+=Step
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'stream' 'is' memberFeature=[ItemFlow|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'stream' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'stream' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'stream' ownedRelatedElement+=AbstractItemFlow
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'stream' ownedRelatedElement+=ItemFlow
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'succession' 'is' memberFeature=[Succession|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'succession' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'succession' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'succession' ownedRelatedElement+=AbstractSuccession
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'succession' ownedRelatedElement+=Succession
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) isComposite?='composite'
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) isPort?='port'
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) isPortion?='portion'
	 *     visibility=VisibilityIndicator (ambiguity) 'binding' 'is' memberFeature=[BindingConnector|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'binding' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'binding' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'binding' ownedRelatedElement+=AbstractBindingConnector
	 *     visibility=VisibilityIndicator (ambiguity) 'binding' ownedRelatedElement+=BindingConnector
	 *     visibility=VisibilityIndicator (ambiguity) 'connector' 'is' memberFeature=[Connector|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'connector' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'connector' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'connector' ownedRelatedElement+=AbstractConnector
	 *     visibility=VisibilityIndicator (ambiguity) 'connector' ownedRelatedElement+=Connector
	 *     visibility=VisibilityIndicator (ambiguity) 'expr' 'is' memberFeature=[Expression|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'expr' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'expr' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'expr' ownedRelatedElement+=AbstractBlockExpression
	 *     visibility=VisibilityIndicator (ambiguity) 'expr' ownedRelatedElement+=BlockExpression
	 *     visibility=VisibilityIndicator (ambiguity) 'feature' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'feature' ownedRelatedElement+=AbstractFeature
	 *     visibility=VisibilityIndicator (ambiguity) 'feature'? 'is' memberFeature=[Feature|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'feature'? direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'feature'? memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'feature'? ownedRelatedElement+=Feature
	 *     visibility=VisibilityIndicator (ambiguity) 'flow' 'is' memberFeature=[SuccessionItemFlow|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'flow' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'flow' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'flow' ownedRelatedElement+=AbstractSuccessionItemFlow
	 *     visibility=VisibilityIndicator (ambiguity) 'flow' ownedRelatedElement+=SuccessionItemFlow
	 *     visibility=VisibilityIndicator (ambiguity) 'step' 'is' memberFeature=[Step|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'step' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'step' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'step' ownedRelatedElement+=AbstractStep
	 *     visibility=VisibilityIndicator (ambiguity) 'step' ownedRelatedElement+=Step
	 *     visibility=VisibilityIndicator (ambiguity) 'stream' 'is' memberFeature=[ItemFlow|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'stream' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'stream' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'stream' ownedRelatedElement+=AbstractItemFlow
	 *     visibility=VisibilityIndicator (ambiguity) 'stream' ownedRelatedElement+=ItemFlow
	 *     visibility=VisibilityIndicator (ambiguity) 'succession' 'is' memberFeature=[Succession|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'succession' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'succession' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'succession' ownedRelatedElement+=AbstractSuccession
	 *     visibility=VisibilityIndicator (ambiguity) 'succession' ownedRelatedElement+=Succession
	 *     visibility=VisibilityIndicator (ambiguity) isComposite?='composite'
	 *     visibility=VisibilityIndicator (ambiguity) isPort?='port'
	 *     visibility=VisibilityIndicator (ambiguity) isPortion?='portion'
	 */
	protected void emit_EndFeatureMember_EndKeyword_1_0_0_or___AbstractKeyword_1_1_0_EndKeyword_1_1_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ':>>' | 'redefines'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) ownedRelationship+=Redefinition
	 */
	protected void emit_ExpressionDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ':>>' | 'redefines'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'feature' (ambiguity) ownedRelationship+=Redefinition
	 *     (rule start) (ambiguity) ownedRelationship+=Redefinition
	 *     isAbstract?='abstract' 'feature' (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=ElementImport 'feature' (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=PackageImport 'feature' (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=PrefixAnnotation 'feature' (ambiguity) ownedRelationship+=Redefinition
	 */
	protected void emit_FeatureDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'feature'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'abstract'? (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     (rule start) 'abstract'? (ambiguity) direction=FeatureDirection
	 *     (rule start) 'abstract'? (ambiguity) memberName=Name
	 *     (rule start) 'abstract'? (ambiguity) ownedRelatedElement+=Feature
	 *     (rule start) 'end' (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     (rule start) 'end' (ambiguity) direction=FeatureDirection
	 *     (rule start) 'end' (ambiguity) memberName=Name
	 *     (rule start) 'end' (ambiguity) ownedRelatedElement+=Feature
	 *     (rule start) ('end' | ('abstract' 'end')) (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     (rule start) ('end' | ('abstract' 'end')) (ambiguity) direction=FeatureDirection
	 *     (rule start) ('end' | ('abstract' 'end')) (ambiguity) memberName=Name
	 *     (rule start) ('end' | ('abstract' 'end')) (ambiguity) ownedRelatedElement+=Feature
	 *     (rule start) (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     (rule start) (ambiguity) direction=FeatureDirection
	 *     (rule start) (ambiguity) memberName=Name
	 *     (rule start) (ambiguity) ownedRelatedElement+=Feature
	 *     isComposite?='composite' (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     isComposite?='composite' (ambiguity) direction=FeatureDirection
	 *     isComposite?='composite' (ambiguity) memberName=Name
	 *     isComposite?='composite' (ambiguity) ownedRelatedElement+=Feature
	 *     isPort?='port' (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     isPort?='port' (ambiguity) direction=FeatureDirection
	 *     isPort?='port' (ambiguity) memberName=Name
	 *     isPort?='port' (ambiguity) ownedRelatedElement+=Feature
	 *     isPortion?='portion' (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     isPortion?='portion' (ambiguity) direction=FeatureDirection
	 *     isPortion?='portion' (ambiguity) memberName=Name
	 *     isPortion?='portion' (ambiguity) ownedRelatedElement+=Feature
	 *     ownedRelationship+=PrefixAnnotation 'abstract'? (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation 'abstract'? (ambiguity) direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation 'abstract'? (ambiguity) memberName=Name
	 *     ownedRelationship+=PrefixAnnotation 'abstract'? (ambiguity) ownedRelatedElement+=Feature
	 *     ownedRelationship+=PrefixAnnotation 'end' (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation 'end' (ambiguity) direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation 'end' (ambiguity) memberName=Name
	 *     ownedRelationship+=PrefixAnnotation 'end' (ambiguity) ownedRelatedElement+=Feature
	 *     ownedRelationship+=PrefixAnnotation ('end' | ('abstract' 'end')) (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation ('end' | ('abstract' 'end')) (ambiguity) direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation ('end' | ('abstract' 'end')) (ambiguity) memberName=Name
	 *     ownedRelationship+=PrefixAnnotation ('end' | ('abstract' 'end')) (ambiguity) ownedRelatedElement+=Feature
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) ownedRelatedElement+=Feature
	 *     visibility=VisibilityIndicator 'abstract'? (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     visibility=VisibilityIndicator 'abstract'? (ambiguity) direction=FeatureDirection
	 *     visibility=VisibilityIndicator 'abstract'? (ambiguity) memberName=Name
	 *     visibility=VisibilityIndicator 'abstract'? (ambiguity) ownedRelatedElement+=Feature
	 *     visibility=VisibilityIndicator 'end' (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     visibility=VisibilityIndicator 'end' (ambiguity) direction=FeatureDirection
	 *     visibility=VisibilityIndicator 'end' (ambiguity) memberName=Name
	 *     visibility=VisibilityIndicator 'end' (ambiguity) ownedRelatedElement+=Feature
	 *     visibility=VisibilityIndicator ('end' | ('abstract' 'end')) (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     visibility=VisibilityIndicator ('end' | ('abstract' 'end')) (ambiguity) direction=FeatureDirection
	 *     visibility=VisibilityIndicator ('end' | ('abstract' 'end')) (ambiguity) memberName=Name
	 *     visibility=VisibilityIndicator ('end' | ('abstract' 'end')) (ambiguity) ownedRelatedElement+=Feature
	 *     visibility=VisibilityIndicator (ambiguity) 'is' memberFeature=[Feature|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) ownedRelatedElement+=Feature
	 */
	protected void emit_FeatureMemberElement_FeatureKeyword_0_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'abstract'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'binding' 'is' memberFeature=[BindingConnector|QualifiedName]
	 *     (rule start) (ambiguity) 'binding' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'binding' memberName=Name
	 *     (rule start) (ambiguity) 'binding' ownedRelatedElement+=AbstractBindingConnector
	 *     (rule start) (ambiguity) 'binding' ownedRelatedElement+=BindingConnector
	 *     (rule start) (ambiguity) 'connector' 'is' memberFeature=[Connector|QualifiedName]
	 *     (rule start) (ambiguity) 'connector' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'connector' memberName=Name
	 *     (rule start) (ambiguity) 'connector' ownedRelatedElement+=AbstractConnector
	 *     (rule start) (ambiguity) 'connector' ownedRelatedElement+=Connector
	 *     (rule start) (ambiguity) 'expr' 'is' memberFeature=[Expression|QualifiedName]
	 *     (rule start) (ambiguity) 'expr' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'expr' memberName=Name
	 *     (rule start) (ambiguity) 'expr' ownedRelatedElement+=AbstractBlockExpression
	 *     (rule start) (ambiguity) 'expr' ownedRelatedElement+=BlockExpression
	 *     (rule start) (ambiguity) 'feature' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'feature' ownedRelatedElement+=AbstractFeature
	 *     (rule start) (ambiguity) 'feature'? 'is' memberFeature=[Feature|QualifiedName]
	 *     (rule start) (ambiguity) 'feature'? direction=FeatureDirection
	 *     (rule start) (ambiguity) 'feature'? memberName=Name
	 *     (rule start) (ambiguity) 'feature'? ownedRelatedElement+=Feature
	 *     (rule start) (ambiguity) 'flow' 'is' memberFeature=[SuccessionItemFlow|QualifiedName]
	 *     (rule start) (ambiguity) 'flow' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'flow' memberName=Name
	 *     (rule start) (ambiguity) 'flow' ownedRelatedElement+=AbstractSuccessionItemFlow
	 *     (rule start) (ambiguity) 'flow' ownedRelatedElement+=SuccessionItemFlow
	 *     (rule start) (ambiguity) 'step' 'is' memberFeature=[Step|QualifiedName]
	 *     (rule start) (ambiguity) 'step' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'step' memberName=Name
	 *     (rule start) (ambiguity) 'step' ownedRelatedElement+=AbstractStep
	 *     (rule start) (ambiguity) 'step' ownedRelatedElement+=Step
	 *     (rule start) (ambiguity) 'stream' 'is' memberFeature=[ItemFlow|QualifiedName]
	 *     (rule start) (ambiguity) 'stream' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'stream' memberName=Name
	 *     (rule start) (ambiguity) 'stream' ownedRelatedElement+=AbstractItemFlow
	 *     (rule start) (ambiguity) 'stream' ownedRelatedElement+=ItemFlow
	 *     (rule start) (ambiguity) 'succession' 'is' memberFeature=[Succession|QualifiedName]
	 *     (rule start) (ambiguity) 'succession' direction=FeatureDirection
	 *     (rule start) (ambiguity) 'succession' memberName=Name
	 *     (rule start) (ambiguity) 'succession' ownedRelatedElement+=AbstractSuccession
	 *     (rule start) (ambiguity) 'succession' ownedRelatedElement+=Succession
	 *     (rule start) (ambiguity) isComposite?='composite'
	 *     (rule start) (ambiguity) isPort?='port'
	 *     (rule start) (ambiguity) isPortion?='portion'
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'binding' 'is' memberFeature=[BindingConnector|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'binding' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'binding' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'binding' ownedRelatedElement+=AbstractBindingConnector
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'binding' ownedRelatedElement+=BindingConnector
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'connector' 'is' memberFeature=[Connector|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'connector' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'connector' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'connector' ownedRelatedElement+=AbstractConnector
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'connector' ownedRelatedElement+=Connector
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'expr' 'is' memberFeature=[Expression|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'expr' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'expr' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'expr' ownedRelatedElement+=AbstractBlockExpression
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'expr' ownedRelatedElement+=BlockExpression
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature' ownedRelatedElement+=AbstractFeature
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature'? 'is' memberFeature=[Feature|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature'? direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature'? memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'feature'? ownedRelatedElement+=Feature
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'flow' 'is' memberFeature=[SuccessionItemFlow|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'flow' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'flow' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'flow' ownedRelatedElement+=AbstractSuccessionItemFlow
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'flow' ownedRelatedElement+=SuccessionItemFlow
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'step' 'is' memberFeature=[Step|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'step' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'step' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'step' ownedRelatedElement+=AbstractStep
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'step' ownedRelatedElement+=Step
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'stream' 'is' memberFeature=[ItemFlow|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'stream' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'stream' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'stream' ownedRelatedElement+=AbstractItemFlow
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'stream' ownedRelatedElement+=ItemFlow
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'succession' 'is' memberFeature=[Succession|QualifiedName]
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'succession' direction=FeatureDirection
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'succession' memberName=Name
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'succession' ownedRelatedElement+=AbstractSuccession
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) 'succession' ownedRelatedElement+=Succession
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) isComposite?='composite'
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) isPort?='port'
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) isPortion?='portion'
	 *     visibility=VisibilityIndicator (ambiguity) 'binding' 'is' memberFeature=[BindingConnector|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'binding' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'binding' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'binding' ownedRelatedElement+=AbstractBindingConnector
	 *     visibility=VisibilityIndicator (ambiguity) 'binding' ownedRelatedElement+=BindingConnector
	 *     visibility=VisibilityIndicator (ambiguity) 'connector' 'is' memberFeature=[Connector|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'connector' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'connector' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'connector' ownedRelatedElement+=AbstractConnector
	 *     visibility=VisibilityIndicator (ambiguity) 'connector' ownedRelatedElement+=Connector
	 *     visibility=VisibilityIndicator (ambiguity) 'expr' 'is' memberFeature=[Expression|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'expr' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'expr' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'expr' ownedRelatedElement+=AbstractBlockExpression
	 *     visibility=VisibilityIndicator (ambiguity) 'expr' ownedRelatedElement+=BlockExpression
	 *     visibility=VisibilityIndicator (ambiguity) 'feature' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'feature' ownedRelatedElement+=AbstractFeature
	 *     visibility=VisibilityIndicator (ambiguity) 'feature'? 'is' memberFeature=[Feature|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'feature'? direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'feature'? memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'feature'? ownedRelatedElement+=Feature
	 *     visibility=VisibilityIndicator (ambiguity) 'flow' 'is' memberFeature=[SuccessionItemFlow|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'flow' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'flow' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'flow' ownedRelatedElement+=AbstractSuccessionItemFlow
	 *     visibility=VisibilityIndicator (ambiguity) 'flow' ownedRelatedElement+=SuccessionItemFlow
	 *     visibility=VisibilityIndicator (ambiguity) 'step' 'is' memberFeature=[Step|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'step' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'step' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'step' ownedRelatedElement+=AbstractStep
	 *     visibility=VisibilityIndicator (ambiguity) 'step' ownedRelatedElement+=Step
	 *     visibility=VisibilityIndicator (ambiguity) 'stream' 'is' memberFeature=[ItemFlow|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'stream' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'stream' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'stream' ownedRelatedElement+=AbstractItemFlow
	 *     visibility=VisibilityIndicator (ambiguity) 'stream' ownedRelatedElement+=ItemFlow
	 *     visibility=VisibilityIndicator (ambiguity) 'succession' 'is' memberFeature=[Succession|QualifiedName]
	 *     visibility=VisibilityIndicator (ambiguity) 'succession' direction=FeatureDirection
	 *     visibility=VisibilityIndicator (ambiguity) 'succession' memberName=Name
	 *     visibility=VisibilityIndicator (ambiguity) 'succession' ownedRelatedElement+=AbstractSuccession
	 *     visibility=VisibilityIndicator (ambiguity) 'succession' ownedRelatedElement+=Succession
	 *     visibility=VisibilityIndicator (ambiguity) isComposite?='composite'
	 *     visibility=VisibilityIndicator (ambiguity) isPort?='port'
	 *     visibility=VisibilityIndicator (ambiguity) isPortion?='portion'
	 */
	protected void emit_FeatureMember_AbstractKeyword_1_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';' | ('{' '}')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     isNonunique?='nonunique' (ambiguity) (rule end)
	 *     isOrdered?='ordered' (ambiguity) (rule end)
	 *     isSufficient?='all' 'any' (ambiguity) (rule end)
	 *     name=Name (ambiguity) (rule end)
	 *     ownedRelationship+=FeatureTyping (ambiguity) (rule end)
	 *     ownedRelationship+=FeatureValue (ambiguity) (rule end)
	 *     ownedRelationship+=Multiplicity (ambiguity) (rule end)
	 *     ownedRelationship+=Redefinition (ambiguity) (rule end)
	 *     ownedRelationship+=ReturnParameterMember (ambiguity) (rule end)
	 *     ownedRelationship+=Subset (ambiguity) (rule end)
	 *     ownedRelationship+=Superclassing (ambiguity) (rule end)
	 */
	protected void emit_FunctionBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'feature'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) ownedRelatedElement+=Feature
	 *     ownedRelationship+=PrefixAnnotation (ambiguity) ownedRelatedElement+=Feature
	 *     visibility=PackageElementVisibilityIndicator (ambiguity) ownedRelatedElement+=Feature
	 */
	protected void emit_PackageFeatureMemberElement_FeatureKeyword_0_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'feature'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'abstract' (ambiguity) ownedRelatedElement+=AbstractFeature
	 *     ownedRelationship+=PrefixAnnotation 'abstract' (ambiguity) ownedRelatedElement+=AbstractFeature
	 *     visibility=PackageElementVisibilityIndicator 'abstract' (ambiguity) ownedRelatedElement+=AbstractFeature
	 */
	protected void emit_PackageFeatureMemberElement_FeatureKeyword_2_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '::' | '.'
	 *
	 * This ambiguous syntax occurs at:
	 *     importedPackage=[Package|Name] (ambiguity) '*' ';' (rule end)
	 */
	protected void emit_PackageImport_ColonColonKeyword_3_0_1_0_or_FullStopKeyword_3_0_1_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     './'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '('* (ambiguity) ownedRelationship+=FeatureReference
	 */
	protected void emit_QueryHeadExpression_FullStopSolidusKeyword_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ':>>' | 'redefines'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) ':' 'any' (ambiguity) ownedRelationship+=Redefinition
	 *     (rule start) 'feature' ':' 'any' (ambiguity) ownedRelationship+=Redefinition
	 *     isAbstract?='abstract' 'feature' ':' 'any' (ambiguity) ownedRelationship+=Redefinition
	 *     isNonunique?='nonunique' (ambiguity) ownedRelationship+=Redefinition
	 *     isOrdered?='ordered' (ambiguity) ownedRelationship+=Redefinition
	 *     isSufficient?='all' 'any' (ambiguity) ownedRelationship+=Redefinition
	 *     name=Name (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=ElementImport 'feature' ':' 'any' (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=FeatureTyping (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=Multiplicity (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=PackageImport 'feature' ':' 'any' (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=ParameterMember ')' (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=PrefixAnnotation 'feature' ':' 'any' (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=Redefinition ':' 'any' (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=Redefinition (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=ReturnParameterMember (ambiguity) ownedRelationship+=Redefinition
	 *     ownedRelationship+=Subset (ambiguity) ownedRelationship+=Redefinition
	 */
	protected void emit_Redefines_ColonGreaterThanSignGreaterThanSignKeyword_0_0_or_RedefinesKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ':>' | 'specializes'
	 *
	 * This ambiguous syntax occurs at:
	 *     name=Name (ambiguity) ownedRelationship+=Superclassing
	 *     ownedRelationship+=ParameterMember ')' (ambiguity) ownedRelationship+=Superclassing
	 *     ownedRelationship+=ReturnParameterMember (ambiguity) ownedRelationship+=Superclassing
	 */
	protected void emit_SpecializationList_ColonGreaterThanSignKeyword_0_0_or_SpecializesKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ':>>' | 'redefines'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) ownedRelationship+=Redefinition
	 */
	protected void emit_StepDeclaration_ColonGreaterThanSignGreaterThanSignKeyword_2_0_0_or_RedefinesKeyword_2_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ':>' | 'subsets'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) ':' 'any' (ambiguity) ownedRelationship+=Subset
	 *     (rule start) 'feature' ':' 'any' (ambiguity) ownedRelationship+=Subset
	 *     isAbstract?='abstract' 'feature' ':' 'any' (ambiguity) ownedRelationship+=Subset
	 *     isNonunique?='nonunique' (ambiguity) ownedRelationship+=Subset
	 *     isOrdered?='ordered' (ambiguity) ownedRelationship+=Subset
	 *     isSufficient?='all' 'any' (ambiguity) ownedRelationship+=Subset
	 *     name=Name (ambiguity) ownedRelationship+=Subset
	 *     ownedRelationship+=ElementImport 'feature' ':' 'any' (ambiguity) ownedRelationship+=Subset
	 *     ownedRelationship+=FeatureTyping (ambiguity) ownedRelationship+=Subset
	 *     ownedRelationship+=Multiplicity (ambiguity) ownedRelationship+=Subset
	 *     ownedRelationship+=PackageImport 'feature' ':' 'any' (ambiguity) ownedRelationship+=Subset
	 *     ownedRelationship+=ParameterMember ')' (ambiguity) ownedRelationship+=Subset
	 *     ownedRelationship+=PrefixAnnotation 'feature' ':' 'any' (ambiguity) ownedRelationship+=Subset
	 *     ownedRelationship+=Redefinition ':' 'any' (ambiguity) ownedRelationship+=Subset
	 *     ownedRelationship+=Redefinition (ambiguity) ownedRelationship+=Subset
	 *     ownedRelationship+=ReturnParameterMember (ambiguity) ownedRelationship+=Subset
	 *     ownedRelationship+=Subset (ambiguity) ownedRelationship+=Subset
	 */
	protected void emit_Subsets_ColonGreaterThanSignKeyword_0_0_or_SubsetsKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';' | ('{' '}')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) ':' 'any' (ambiguity) (rule start)
	 *     (rule start) 'feature' ':' 'any' (ambiguity) (rule start)
	 *     isAbstract?='abstract' 'feature' ':' 'any' (ambiguity) (rule end)
	 *     isNonunique?='nonunique' (ambiguity) (rule end)
	 *     isOrdered?='ordered' (ambiguity) (rule end)
	 *     isSufficient?='all' 'any' (ambiguity) (rule end)
	 *     name=Name (ambiguity) (rule end)
	 *     ownedRelationship+=ConnectorEndMember ')' (ambiguity) (rule end)
	 *     ownedRelationship+=ConnectorEndMember (ambiguity) (rule end)
	 *     ownedRelationship+=ElementImport 'feature' ':' 'any' (ambiguity) (rule end)
	 *     ownedRelationship+=FeatureTyping (ambiguity) (rule end)
	 *     ownedRelationship+=FeatureValue (ambiguity) (rule end)
	 *     ownedRelationship+=ItemFlowEndMember (ambiguity) (rule end)
	 *     ownedRelationship+=Multiplicity (ambiguity) (rule end)
	 *     ownedRelationship+=PackageImport 'feature' ':' 'any' (ambiguity) (rule end)
	 *     ownedRelationship+=ParameterMember ')' (ambiguity) (rule end)
	 *     ownedRelationship+=PrefixAnnotation 'feature' ':' 'any' (ambiguity) (rule end)
	 *     ownedRelationship+=Redefinition (ambiguity) (rule end)
	 *     ownedRelationship+=Subset (ambiguity) (rule end)
	 *     ownedRelationship+=Superclassing (ambiguity) (rule end)
	 */
	protected void emit_TypeBody_SemicolonKeyword_0_or___LeftCurlyBracketKeyword_1_0_RightCurlyBracketKeyword_1_2__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (':' 'any')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'feature' (ambiguity) ownedRelationship+=Multiplicity
	 *     (rule start) (ambiguity) ownedRelationship+=Multiplicity
	 *     isAbstract?='abstract' 'feature' (ambiguity) ownedRelationship+=Multiplicity
	 *     name=Name (ambiguity) ownedRelationship+=Multiplicity
	 *     ownedRelationship+=ElementImport 'feature' (ambiguity) ownedRelationship+=Multiplicity
	 *     ownedRelationship+=PackageImport 'feature' (ambiguity) ownedRelationship+=Multiplicity
	 *     ownedRelationship+=PrefixAnnotation 'feature' (ambiguity) ownedRelationship+=Multiplicity
	 *     ownedRelationship+=Redefinition (ambiguity) ownedRelationship+=Multiplicity
	 */
	protected void emit_TypePart___ColonKeyword_0_0_AnyKeyword_0_2_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
