<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="structure" nsURI="http://www.openmbee.org/kerml/str" nsPrefix="str">
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="KerML-Core.ecore#//Container">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The generic Model constructor and the generic type of all properties. It has a complete set of sub-sets. While it is permitted to create a Class in SysML2 it is intended that the user would eventually specify further intent for the Class (Block, Behavior, ConstriantBlock, Requirement, etc.). Therefore use of a plain Class would be considered a minor constraint violation that should be addressed of as the maturity of the Model improves&#xA;&#xA;Normative Alias: Definition(SysML2)&#xA;SECM Alias: Definition Element"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificClassifier" ordered="false"
        upperBound="-1" eType="#//Class" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specializations of this Block derived from any Generalization relationships of which block is the source"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalClassifier" ordered="false"
        upperBound="-1" eType="#//Class" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFeature" ordered="false"
        upperBound="-1" eType="#//Feature" containment="true" eOpposite="#//Feature/class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedFeature" ordered="false"
        upperBound="-1" eType="#//Feature" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typesFeature" ordered="false"
        upperBound="-1" eType="#//Feature" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        upperBound="-1" eType="#//Feature" derived="true" eOpposite="#//Feature/featuringClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceOf" ordered="false"
        eType="#//Class" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" ordered="false"
        upperBound="-1" eType="#//Generalization" containment="true" eOpposite="#//Generalization/specific"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedFeatureOfClass" ordered="false"
        upperBound="-1" eType="#//Feature" derived="true" containment="true" eOpposite="#//Feature/context">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A Feature is an ownedRefinement if it has a defined featurePath"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="KerML-Core.ecore#//Relationship #//StructuredClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEndProperty" ordered="false"
        lowerBound="1" eType="#//StructuredFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetParticipantProperty"
        ordered="false" lowerBound="1" eType="#//StructuredFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEndProperty" ordered="false"
        lowerBound="1" eType="#//StructuredFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceParticipantProperty"
        ordered="false" lowerBound="1" eType="#//StructuredFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participantProperty" ordered="false"
        lowerBound="2" upperBound="2" eType="#//StructuredFeature" derived="true"
        eOpposite="#//StructuredFeature/participatesIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endProperty" ordered="false"
        lowerBound="2" upperBound="2" eType="#//StructuredFeature" derived="true"
        eOpposite="#//StructuredFeature/endOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typesConnector" ordered="false"
        upperBound="-1" eType="#//Connector" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="KerML-Core.ecore#//Container">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;html>&#xA;  &lt;head>&#xA;&#x9;&#x9;&lt;style>&#xA;&#x9;&#x9;&#x9;p {padding:0px; margin:0px;}&#xA;&#x9;&#x9;&lt;/style>&#xA;&#x9;&lt;/head>&#xA;  &lt;body>&#xA;    &lt;p>&#xA;&amp;#160;This is called Feature rather than attribute because in UML&amp;#160;Attribute's are more restrictive w.r.t. typing than the intent of KerML&amp;#160;Feature which is more open.&#xA;&#xA;    &lt;/p>&#xA;&#xA;    &lt;p>&#xA;&amp;#160;&#xA;&#xA;    &lt;/p>&#xA;&#xA;    &lt;p>&#xA;Possible Alias: Usage(SysML2)&#xA;&#xA;    &lt;/p>&#xA;&#xA;&lt;/body>&#xA;&lt;/html>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" upperBound="-1"
        eType="#//Class" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" ordered="false"
        eType="#//Class" eOpposite="#//Class/ownedFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedFeature" ordered="false"
        upperBound="-1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsettedFeature" ordered="false"
        upperBound="-1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadOnly" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodVisibility" ordered="false"
        lowerBound="1" eType="ecore:EEnum KerML-Core.ecore#//visibilityKind">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specific Visibility of the feature not the package"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false"
        eType="#//Class" derived="true" eOpposite="#//Class/nestedFeatureOfClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featurePath" upperBound="-1"
        eType="#//FeaturePathNode" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Entries on the featurePath may include other features with featurePath defined as long as the resulting path creates a legal set of M0 instances as specified by the defining model."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestingFeature" ordered="false"
        eType="#//Feature" eOpposite="#//Feature/nestedFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedFeature" ordered="false"
        upperBound="-1" eType="#//Feature" containment="true" eOpposite="#//Feature/nestingFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definingType" ordered="false"
        lowerBound="1" eType="#//Class">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Note that the default instance of definingType is the M1 Library element Any"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refiningType" ordered="false"
        eType="#//Class">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Note that the default instance of refiningType is the M1 Library element Any"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" ordered="false"
        upperBound="-1" eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuringClassifier" ordered="false"
        eType="#//Class" derived="true" eOpposite="#//Class/feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="KerML-Core.ecore#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" ordered="false"
        lowerBound="1" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specific" ordered="false"
        lowerBound="1" eType="#//Class" eOpposite="#//Class/generalization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="KerML-Core.ecore#//Relationship #//StructuredFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePath" lowerBound="1"
        upperBound="-1" eType="#//StructuredFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPath" lowerBound="1"
        upperBound="-1" eType="#//StructuredFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDirected" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceUpper" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceLower" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetUpper" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetLower" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceMultiplicity" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetMultiplicity" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        lowerBound="1" eType="#//RefinedAssociation" eOpposite="#//RefinedAssociation/definingConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredFeature" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPort" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outsideAccess" ordered="false"
        upperBound="2" eType="#//PropertyAccessKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insideAccess" ordered="false"
        upperBound="2" eType="#//PropertyAccessKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="union" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" ordered="false"
        lowerBound="1" eType="#//ValueOption" derived="true" containment="true" eOpposite="#//ValueOption/optionOfProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigable" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" ordered="false"
        eType="#//AggregationKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endOf" ordered="false"
        eType="#//Association" derived="true" eOpposite="#//Association/endProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatesIn" ordered="false"
        eType="#//Association" derived="true" eOpposite="#//Association/participantProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInput" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOutput" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefinedAssociation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definingConnector" ordered="false"
        lowerBound="1" eType="#//Connector" eOpposite="#//Connector/value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceOf" ordered="false"
        eType="#//Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyAccessKind">
    <eLiterals name="read"/>
    <eLiterals name="write"/>
    <eLiterals name="only"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueOption" eSuperTypes="KerML-Core.ecore#//Relationship #//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionOfProperty" ordered="false"
        lowerBound="1" eType="#//StructuredFeature" eOpposite="#//StructuredFeature/option"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AggregationKind">
    <eLiterals name="Composite"/>
    <eLiterals name="Shared"/>
    <eLiterals name="None"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFeature" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" ordered="false"
        lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        upperBound="-1" eType="#//ValueRestriction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" ordered="false"
        lowerBound="1" eType="#//ValueRestriction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredClass" eSuperTypes="#//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredProperty" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedProperty" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEncapsulated" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conjugate" ordered="false"
        lowerBound="1" eType="#//StructuredClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConnector" ordered="false"
        upperBound="-1" eType="#//Connector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStructuredFeature"
        ordered="false" upperBound="-1" eType="#//StructuredFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typesProperty" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blindProperty" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The set of all Property's not owned or required by a StructuredClass and are an endProperty of an Association where the other endProperty has that StructuredClass as its type&#xA;&#xA;FIX ME:&#xA;let assoc:Association = Class.relation->select(schematype==Association) in if assoc.endProperty.type->select(type == Class).size() >= 1 then  endProperty->select(type != Class)&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portProperty" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proxyPort" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selfPort" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fullPort" ordered="false"
        upperBound="-1" eType="#//StructuredFeature" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactionParticipant"
        ordered="false" upperBound="-1" eType="#//StructuredFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralizationSet" eSuperTypes="KerML-Core.ecore#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="complete" ordered="false"
        lowerBound="1" eType="#//Generalization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//Connector"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueRestriction" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeaturePathNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        lowerBound="1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Individual">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Direct specification of a variant&#xA;&#xA;&#xA;Validation rule:&#xA;level=Warning&#xA;Individual tree should include all Feature's that have a defined featurePath&#xA;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definingFeature" ordered="false"
        lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false"
        eType="#//Individual" eOpposite="#//Individual/child"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" ordered="false"
        upperBound="-1" eType="#//Individual" eOpposite="#//Individual/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false"
        lowerBound="1" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Restricts" eSuperTypes="KerML-Core.ecore#//Relationship #//Generalization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="restricted" ordered="false"
        lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restrictedBy" ordered="false"
        lowerBound="1" eType="#//ValueRestriction"/>
  </eClassifiers>
</ecore:EPackage>
