<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sysml" nsURI="http://www.omg.org/spec/SysML/2.0" nsPrefix="sysml">
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Relationship #//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedType" ordered="false"
        unique="false" lowerBound="2" upperBound="-1" eType="#//Class" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEndFeatureMembership"
        lowerBound="2" upperBound="-1" eType="#//EndFeatureMembership" eOpposite="#//EndFeatureMembership/owningAssociation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningConnector" ordered="false"
        eType="#//Connector" eOpposite="#//Connector/ownedAssociationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" eSuperTypes="#//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="takesStep" ordered="false"
        upperBound="-1" eType="#//Step"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvesFeature" ordered="false"
        upperBound="-1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" eSuperTypes="#//Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedGeneralization" ordered="false"
        upperBound="-1" eType="#//Generalization" derived="true" eOpposite="#//Generalization/owningCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFeatureMembership"
        upperBound="-1" eType="#//FeatureMembership" eOpposite="#//FeatureMembership/owningCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        upperBound="-1" eType="#//Feature" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFeature" ordered="false"
        upperBound="-1" eType="#//Feature" derived="true" eOpposite="#//Feature/owningCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" ordered="false"
        upperBound="-1" eType="#//Feature" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" ordered="false"
        upperBound="-1" eType="#//Feature" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Category"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commentedElement" ordered="false"
        lowerBound="1" eType="#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="#//Relationship #//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedFeatures" ordered="false"
        unique="false" lowerBound="2" upperBound="-1" eType="#//Feature" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" ordered="false"
        lowerBound="1" eType="#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDirected" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectorEnd" lowerBound="2"
        upperBound="-1" eType="#//ConnectorEnd" containment="true" eOpposite="#//ConnectorEnd/connector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAssociationType" ordered="false"
        eType="#//Association" derived="true" eOpposite="#//Association/owningConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectorEnd" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lower" ordered="false"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" ordered="false"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" ordered="false"
        lowerBound="1" eType="#//Connector" eOpposite="#//Connector/connectorEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" ordered="false" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" lowerBound="1" upperBound="-1"
        eType="#//Feature" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningMembership" ordered="false"
        eType="#//Membership" eOpposite="#//Membership/ownedMemberElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" ordered="false"
        upperBound="-1" eType="#//Element" containment="true" eOpposite="#//Element/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false"
        eType="#//Element" eOpposite="#//Element/ownedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningNamespace" ordered="false"
        eType="#//Package" eOpposite="#//Package/ownedMember"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementReferenceExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referent" ordered="false"
        lowerBound="1" eType="#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndFeatureMembership" eSuperTypes="#//FeatureMembership">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningAssociation" ordered="false"
        lowerBound="1" eType="#//Association" eOpposite="#//Association/ownedEndFeatureMembership"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//Function"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//Category">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedType" ordered="false"
        upperBound="-1" eType="#//Category" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningCategory" ordered="false"
        eType="#//Category" derived="true" eOpposite="#//Category/ownedFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lower" ordered="false"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" ordered="false"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1"
        upperBound="-1" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" ordered="false"
        upperBound="-1" eType="#//Category" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedFeature" ordered="false"
        upperBound="-1" eType="#//Feature" derived="true" eOpposite="#//Feature/nestingFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestingFeature" ordered="false"
        upperBound="-1" eType="#//Feature" derived="true" eOpposite="#//Feature/nestedFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRedefinition" ordered="false"
        upperBound="-1" eType="#//Redefinition" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSubset" ordered="false"
        upperBound="-1" eType="#//Subset" derived="true" eOpposite="#//Subset/owningFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningFeatureMembership"
        ordered="false" eType="#//FeatureMembership" eOpposite="#//FeatureMembership/ownedFeatureElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isComposite" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="[0..*]" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNonunique" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureAccessExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        lowerBound="1" eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessedFeature" ordered="false"
        lowerBound="1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureMembership" eSuperTypes="#//Membership">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningCategory" ordered="false"
        lowerBound="1" eType="#//Category" eOpposite="#//Category/ownedFeatureMembership"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadOnly" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberFeature" ordered="false"
        lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFeatureElement" ordered="false"
        eType="#//Feature" containment="true" eOpposite="#//Feature/owningFeatureMembership"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPart" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPort" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" ordered="false"
        eType="#//FeatureDirectionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningCategory" ordered="false"
        eType="#//Category" derived="true" eOpposite="#//Category/ownedGeneralization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" ordered="false"
        lowerBound="1" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specific" ordered="false"
        lowerBound="1" eType="#//Category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import" eSuperTypes="#//Relationship">
    <eOperations name="importedMembership" ordered="false" upperBound="-1" eType="#//Membership"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedPackage" ordered="false"
        lowerBound="1" eType="#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selecter" ordered="false"
        eType="#//Predicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importOwningPackage" ordered="false"
        lowerBound="1" eType="#//Package" eOpposite="#//Package/ownedImport"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false"
        lowerBound="1" eType="#//VisibilityKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceCreationExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" ordered="false"
        lowerBound="1" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemFlow" eSuperTypes="#//Connector #//Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemType" unique="false"
        lowerBound="1" upperBound="-1" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetInputFeature" unique="false"
        lowerBound="1" upperBound="-1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceOutputFeature" unique="false"
        lowerBound="1" upperBound="-1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralBoolean" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralInteger" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralNull" eSuperTypes="#//LiteralExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralReal" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralString" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralUnbounded" eSuperTypes="#//LiteralExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Membership" eSuperTypes="#//Relationship">
    <eOperations name="isDistinguishableFrom" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//Membership"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memberName" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false"
        lowerBound="1" eType="#//VisibilityKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aliases" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberElement" ordered="false"
        lowerBound="1" eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMemberElement" ordered="false"
        eType="#//Element" containment="true" eOpposite="#//Element/owningMembership"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="membershipOwningPackage"
        ordered="false" lowerBound="1" eType="#//Package" eOpposite="#//Package/ownedMembership"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OFSuccession">
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" ordered="false" lowerBound="1"
        eType="#//OrderedFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" ordered="false" lowerBound="1"
        eType="#//OrderedFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" upperBound="-1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedFeature" eSuperTypes="#//StructuredFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//Element">
    <eOperations name="nameOf" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="element" ordered="false" lowerBound="1" eType="#//Element"/>
    </eOperations>
    <eOperations name="excludeCollisions" ordered="false" upperBound="-1" eType="#//Membership">
      <eParameters name="mem" ordered="false" upperBound="-1" eType="#//Membership"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="membership" upperBound="-1"
        eType="#//Membership" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedImport" upperBound="-1"
        eType="#//Import" containment="true" eOpposite="#//Import/importOwningPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" upperBound="-1"
        eType="#//Element" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMember" upperBound="-1"
        eType="#//Element" derived="true" eOpposite="#//Element/owningNamespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMembership" upperBound="-1"
        eType="#//Membership" containment="true" eOpposite="#//Membership/membershipOwningPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedMembership" upperBound="-1"
        eType="#//Membership" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predicate" eSuperTypes="#//Function"/>
  <eClassifiers xsi:type="ecore:EClass" name="Redefinition" eSuperTypes="#//Subset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefiningFeature" ordered="false"
        lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedFeature" ordered="false"
        lowerBound="1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="related" ordered="false"
        unique="false" lowerBound="2" upperBound="-1" eType="#//Element" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        upperBound="-1" eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        upperBound="-1" eType="#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceAccessExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primary" ordered="false"
        lowerBound="1" eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" ordered="false"
        lowerBound="1" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceConstructionExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredFeature" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Subset" eSuperTypes="#//Generalization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsettedFeature" ordered="false"
        lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsettingFeature" ordered="false"
        lowerBound="1" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningFeature" ordered="false"
        eType="#//Feature" derived="true" eOpposite="#//Feature/ownedSubset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Succession" eSuperTypes="#//Connector"/>
  <eClassifiers xsi:type="ecore:EClass" name="SuccessionItemFlow" eSuperTypes="#//ItemFlow #//Succession"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FeatureDirectionKind">
    <eLiterals name="in"/>
    <eLiterals name="out"/>
    <eLiterals name="inout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisibilityKind">
    <eLiterals name="public"/>
    <eLiterals name="private"/>
    <eLiterals name="protected"/>
    <eLiterals name="package"/>
  </eClassifiers>
</ecore:EPackage>
