<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behaviors" nsURI="http://www.omg.org/spec/SysML/2.0/Behavior"
    nsPrefix="behaviors">
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" eSuperTypes="SysML-Classification.ecore#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="Predicate" eSuperTypes="#//Function"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//Function"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralInteger" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralUnbounded" eSuperTypes="#//Expression"/>
</ecore:EPackage>
