/*
 * generated by Xtext 2.24.0
 */
package org.omg.kerml.expressions.xtext.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class KerMLExpressionsProposalProvider extends AbstractKerMLExpressionsProposalProvider {
}
