/**
 * generated by Xtext 2.18.0.M3
 */
package org.omg.kerml.owl.owl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Property Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.omg.kerml.owl.owl.ObjectPropertyExpression#getObjectProperty <em>Object Property</em>}</li>
 * </ul>
 *
 * @see org.omg.kerml.owl.owl.OwlPackage#getObjectPropertyExpression()
 * @model
 * @generated
 */
public interface ObjectPropertyExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Object Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object Property</em>' attribute.
   * @see #setObjectProperty(String)
   * @see org.omg.kerml.owl.owl.OwlPackage#getObjectPropertyExpression_ObjectProperty()
   * @model
   * @generated
   */
  String getObjectProperty();

  /**
   * Sets the value of the '{@link org.omg.kerml.owl.owl.ObjectPropertyExpression#getObjectProperty <em>Object Property</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object Property</em>' attribute.
   * @see #getObjectProperty()
   * @generated
   */
  void setObjectProperty(String value);

} // ObjectPropertyExpression
