/**
 * generated by Xtext 2.18.0.M3
 */
package org.omg.kerml.owl.owl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Class Of</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.omg.kerml.owl.owl.SubClassOf#getSubClassExpression <em>Sub Class Expression</em>}</li>
 *   <li>{@link org.omg.kerml.owl.owl.SubClassOf#getSuperClassExpression <em>Super Class Expression</em>}</li>
 * </ul>
 *
 * @see org.omg.kerml.owl.owl.OwlPackage#getSubClassOf()
 * @model
 * @generated
 */
public interface SubClassOf extends ClassAxiom
{
  /**
   * Returns the value of the '<em><b>Sub Class Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Class Expression</em>' containment reference.
   * @see #setSubClassExpression(ClassExpression)
   * @see org.omg.kerml.owl.owl.OwlPackage#getSubClassOf_SubClassExpression()
   * @model containment="true"
   * @generated
   */
  ClassExpression getSubClassExpression();

  /**
   * Sets the value of the '{@link org.omg.kerml.owl.owl.SubClassOf#getSubClassExpression <em>Sub Class Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Class Expression</em>' containment reference.
   * @see #getSubClassExpression()
   * @generated
   */
  void setSubClassExpression(ClassExpression value);

  /**
   * Returns the value of the '<em><b>Super Class Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Class Expression</em>' containment reference.
   * @see #setSuperClassExpression(ClassExpression)
   * @see org.omg.kerml.owl.owl.OwlPackage#getSubClassOf_SuperClassExpression()
   * @model containment="true"
   * @generated
   */
  ClassExpression getSuperClassExpression();

  /**
   * Sets the value of the '{@link org.omg.kerml.owl.owl.SubClassOf#getSuperClassExpression <em>Super Class Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Class Expression</em>' containment reference.
   * @see #getSuperClassExpression()
   * @generated
   */
  void setSuperClassExpression(ClassExpression value);

} // SubClassOf
