/**
 * generated by Xtext 2.12.0
 */
package org.omg.sysml.usage.sysML.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.omg.sysml.usage.sysML.SysMLPackage;
import org.omg.sysml.usage.sysML.UpperBound;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Upper Bound</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.omg.sysml.usage.sysML.impl.UpperBoundImpl#getValue <em>Value</em>}</li>
 *   <li>{@link org.omg.sysml.usage.sysML.impl.UpperBoundImpl#getVar <em>Var</em>}</li>
 *   <li>{@link org.omg.sysml.usage.sysML.impl.UpperBoundImpl#isUnbounded <em>Unbounded</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UpperBoundImpl extends MinimalEObjectImpl.Container implements UpperBound
{
  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final int VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected int value = VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getVar() <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected static final String VAR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVar() <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected String var = VAR_EDEFAULT;

  /**
   * The default value of the '{@link #isUnbounded() <em>Unbounded</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnbounded()
   * @generated
   * @ordered
   */
  protected static final boolean UNBOUNDED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isUnbounded() <em>Unbounded</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnbounded()
   * @generated
   * @ordered
   */
  protected boolean unbounded = UNBOUNDED_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UpperBoundImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLPackage.Literals.UPPER_BOUND;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(int newValue)
  {
    int oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLPackage.UPPER_BOUND__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getVar()
  {
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVar(String newVar)
  {
    String oldVar = var;
    var = newVar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLPackage.UPPER_BOUND__VAR, oldVar, var));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isUnbounded()
  {
    return unbounded;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnbounded(boolean newUnbounded)
  {
    boolean oldUnbounded = unbounded;
    unbounded = newUnbounded;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLPackage.UPPER_BOUND__UNBOUNDED, oldUnbounded, unbounded));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SysMLPackage.UPPER_BOUND__VALUE:
        return getValue();
      case SysMLPackage.UPPER_BOUND__VAR:
        return getVar();
      case SysMLPackage.UPPER_BOUND__UNBOUNDED:
        return isUnbounded();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SysMLPackage.UPPER_BOUND__VALUE:
        setValue((Integer)newValue);
        return;
      case SysMLPackage.UPPER_BOUND__VAR:
        setVar((String)newValue);
        return;
      case SysMLPackage.UPPER_BOUND__UNBOUNDED:
        setUnbounded((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SysMLPackage.UPPER_BOUND__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
      case SysMLPackage.UPPER_BOUND__VAR:
        setVar(VAR_EDEFAULT);
        return;
      case SysMLPackage.UPPER_BOUND__UNBOUNDED:
        setUnbounded(UNBOUNDED_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SysMLPackage.UPPER_BOUND__VALUE:
        return value != VALUE_EDEFAULT;
      case SysMLPackage.UPPER_BOUND__VAR:
        return VAR_EDEFAULT == null ? var != null : !VAR_EDEFAULT.equals(var);
      case SysMLPackage.UPPER_BOUND__UNBOUNDED:
        return unbounded != UNBOUNDED_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (value: ");
    result.append(value);
    result.append(", var: ");
    result.append(var);
    result.append(", unbounded: ");
    result.append(unbounded);
    result.append(')');
    return result.toString();
  }

} //UpperBoundImpl
