/*
 * generated by Xtext 2.18.0.M3
 */
package org.omg.sysml.owl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.omg.sysml.owl.ui.internal.OwlActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OwlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(OwlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		OwlActivator activator = OwlActivator.getInstance();
		return activator != null ? activator.getInjector(OwlActivator.ORG_OMG_SYSML_OWL_OWL) : null;
	}

}
