#
bin.includes = META-INF/,\
               plugin.properties,\
               lib/org.omg.sysml.model-0.58.0-SNAPSHOT.jar,\
               model/
jars.extra.classpath = lib/org.omg.sysml.model-0.58.0-SNAPSHOT.jar