/**
 * generated by Xtext 2.12.0
 */
package org.omg.sysml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.omg.sysml.ui.AbstractAlfUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AlfUiModule extends AbstractAlfUiModule {
  public AlfUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
